### PR TITLE
Feature/job openings

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/102)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsCategoriesViewController.m, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZdwKBgRhKTA2KhJks:-KcZdwKBgRhKTA2KhJkt:bwb9n5c) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsCategoriesViewController.m#L39)):*
> ```objc
> #pragma mark - Navigation
> 
> - (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
> ```

Run formatter

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m, line 17 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZe9qWVJ4kmDDhLSnd:-KcZe9qXWetav6kboAVG:bt061d8) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m#L17)):*
> ```objc
> @property (weak, nonatomic) IBOutlet UILabel *idLabel;
> @property (weak, nonatomic) IBOutlet UILabel *opensLabel;
> @property (weak, nonatomic) IBOutlet UIWebView *descriptionView;
> ```

Check to see if we should use the ByuWebView. I think there is one, but I don't know what functionality it adds...

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZeHO53Rk2BBH-x11M:-KcZeHO6Q2VmqTVXcvF8:b-oc8orh) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m#L26)):*
> ```objc
>     [super viewDidLoad];
>     
>     self.titleLabel.text = self.posting.postingTitle;
> ```

Is this different from the navigation title?
```objective-c
self.title = self.posting.postingTitle;
```

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m, line 32 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZe2QXmOS41NrnvPA2:-KcZe2QXmOS41NrnvPA3:bry8itr) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m#L32)):*
> ```objc
>     NSString *htmlString = [self.posting.jobDescription stringByDecodingHTMLEntities];
>     [self.descriptionView.scrollView setShowsVerticalScrollIndicator:YES];
>     [self.descriptionView.scrollView setShowsHorizontalScrollIndicator:YES];
> ```

Do we need the horizontal? Can we put this in the storyboard?

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m, line 37 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZejNbAnn7HdTtLfd7:-KcZejNbAnn7HdTtLfd8:b2s2ria) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m#L37)):*
> ```objc
> 
> -(void)webViewDidFinishLoad:(UIWebView *)webView {
>     [self.descriptionView.scrollView flashScrollIndicators];
> ```

What is this?

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsFamilyViewController.m, line 67 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZfFmLa6wh3QgVOZHe:-KcZfFmLa6wh3QgVOZHf:bw435g8) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsFamilyViewController.m#L67)):*
> ```objc
>         return @"";
>     } else if (self.families.count == 0) {
>         return @"No Job Openings";
> ```

Instead of this, let's actually create a footer with the text in the storyboard. Then we'll just set the visibility to true if no families come back

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsPostingsViewController.m, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZfThyRDLeZKmf_4YS:-KcZfThyRDLeZKmf_4YT:bpr7i5f) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsPostingsViewController.m#L23)):*
> ```objc
>     [super viewDidLoad];
>     
>     self.navigationItem.title = self.family.jobTitle;
> ```

You can just use self.title here

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsClient.h, line 16 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZfcfZ3rb5lekHTTB-:-KcZfcfZ3rb5lekHTTB0:b-ehm2oj) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/model/JobOpeningsClient.h#L16)):*
> ```objc
> 
> +(void)getJobCategoriesWithCallBack:(void (^)(NSArray<JobOpeningsCategory *> *categories, ByuError *error))callback;
> +(void)getJobPostingsWithCategory:(JobOpeningsCategory *)category andCallBack:(void (^)(NSArray<JobOpeningsFamily *> *families, ByuError *error))callback;
> ```

If you only need the id, just pass the id in

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsFamily.m, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZfkTgdhpaJobUs6u7:-KcZfkTgdhpaJobUs6u8:bc2ted) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/model/JobOpeningsFamily.m#L20)):*
> ```objc
>     me.jobTemplateId = [dictionary nullSafeObjectForKey:@"job_template_id"];
>     me.jobTitle = [dictionary nullSafeObjectForKey:@"job_title"];
>     id listingData = [dictionary nullSafeObjectForKey:@"job_listing"];
> ```

Comment about why you had to do this

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 3750 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZfvEyfUAemz--03-B:-KcZfvEyfUAemz--03-C:b-t8g5kg) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/byuSuite.xcodeproj/project.pbxproj#L3750)):*
> ```
> 				75DCE5BB1799CE25006E14B5 /* ByuJobOpeningsFamilyTableViewController.h */,
> 				75DCE5BC1799CE25006E14B5 /* ByuJobOpeningsFamilyTableViewController.m */,
> 				75DCE5BD1799CE25006E14B5 /* ByuJobOpeningsFamilyTableViewController.xib */,
> ```

Why didn't things like this get removed? Double check that you removed all the old stuff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102)*

**Comment by ecbrady** [comment]
Review status: 11 of 19 files reviewed at latest revision, 10 unresolved discussions.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsCategoriesViewController.m, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZdwKBgRhKTA2KhJks:-KcZgqalRK-dr8LOaD6E:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsCategoriesViewController.m#L39)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Run formatter
</blockquote></details>

Done.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m, line 17 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZe9qWVJ4kmDDhLSnd:-KcZhlj2ZvhuB2YtTPXL:b-6iz4b8) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Check to see if we should use the ByuWebView. I think there is one, but I don't know what functionality it adds...
</blockquote></details>

Looking through ByuWebView I don't think there's any added functionality for just displaying an HTML string like we're doing here.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZeHO53Rk2BBH-x11M:-KcZhyRgtgtDIyaxZdE9:b-7tx9z7) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m#L26)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is this different from the navigation title?
```objective-c
self.title = self.posting.postingTitle;
```
</blockquote></details>

No this is the label I created in the storyboard for the job title. The navigation title is set to Posting in the old code so I just set that in the Storyboard itself. It wouldn't work to use this title as the navigation title since these titles are often quite long.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m, line 32 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZe2QXmOS41NrnvPA2:-KcZiNbbXzie4E0QjC1s:b-2zustf) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we need the horizontal? Can we put this in the storyboard?
</blockquote></details>

It can't be set in the storyboard. We don't need horizontal.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m, line 37 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZejNbAnn7HdTtLfd7:-KcZiY6iFM99GJ9fJ7ne:b5os87n) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m#L37)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

This displays the scroll bar for a second or two after the text is loaded so the user knows they can scroll. Otherwise it is not so apparent. 

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsFamilyViewController.m, line 67 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZfFmLa6wh3QgVOZHe:-KcdE4dklUk3nPAqIz9m:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsFamilyViewController.m#L67)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Instead of this, let's actually create a footer with the text in the storyboard. Then we'll just set the visibility to true if no families come back
</blockquote></details>

Done.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsPostingsViewController.m, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZfThyRDLeZKmf_4YS:-KcZjKW2nktCwg_TXNy1:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsPostingsViewController.m#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You can just use self.title here
</blockquote></details>

Done.

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsClient.h, line 16 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZfcfZ3rb5lekHTTB-:-KcZjikIuYVNG29oU0dg:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/model/JobOpeningsClient.h#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

If you only need the id, just pass the id in
</blockquote></details>

Done.

---

*[byuSuite/Apps/JobOpenings/model/JobOpeningsFamily.m, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZfkTgdhpaJobUs6u7:-KcZjz9SaS7iqOpO-59J:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/model/JobOpeningsFamily.m#L20)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment about why you had to do this
</blockquote></details>

Done.

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 3750 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZfvEyfUAemz--03-B:-KcZh6Q5qmE08pmsiwc7:b-aksy3f) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/byuSuite.xcodeproj/project.pbxproj#L3750)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why didn't things like this get removed? Double check that you removed all the old stuff
</blockquote></details>

I haven't removed the old stuff yet. I was going to do that at the very end in case I needed to review the old code one last time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102)*

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m, line 37 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZejNbAnn7HdTtLfd7:-KcdL901R8D4lycqeGSF:b379ubu) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m#L37)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

This displays the scroll bar for a second or two after the text is loaded so the user knows they can scroll. Otherwise it is not so apparent. 
</blockquote></details>

Put a comment

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 3750 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZfvEyfUAemz--03-B:-KcdLPmhkfvhSKBcKCNm:bd1zt3s) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/byuSuite.xcodeproj/project.pbxproj#L3750)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

I haven't removed the old stuff yet. I was going to do that at the very end in case I needed to review the old code one last time.
</blockquote></details>

Deal. Let's nuke it now. The rest look good :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102)*

**Comment by ecbrady** [comment]
Review status: 17 of 37 files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m, line 37 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZejNbAnn7HdTtLfd7:-KcdMDfDwSQzw6qVAC_V:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/Apps/JobOpenings/controller/JobOpeningsDetailViewController.m#L37)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Put a comment
</blockquote></details>

Done.

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 3750 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102#-KcZfvEyfUAemz--03-B:-KcdMZvvibTbsfe0loDC:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/fc3f5fe2261e489d99030cc206f7e1733d14d760/byuSuite/byuSuite.xcodeproj/project.pbxproj#L3750)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Deal. Let's nuke it now. The rest look good :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102)*

**Comment by romrell4** [comment]
Reviewed 20 of 20 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/102)*

**Pull request merged**
