### PR TITLE
Hotfix/person directory

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/93)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[byuSuite/BYUMobileAppManifest.json, line 540 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4jWh1KF3g1wk3O2vD:-Kc4jWh1KF3g1wk3O2vE:b-2n4gfl) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/BYUMobileAppManifest.json#L540)):*
> ```JSON
>             "Icon_iOS" : "PersonDirectory",
>             "Storyboard_iOS" : "PersonDirectorySearch",
>             "Storyboard_iPad_iOS" : null,
> ```

Was this the last one using iPad storyboards in the manifest?

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 58 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4jgNKLXE10GmFiwHR:-Kc4jgNKLXE10GmFiwHS:bec503j) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L58)):*
> ```objc
>     
>     [self.tableView applyBYUFormattingHidingEmptyCells];
>     self.tableView.backgroundColor = [UIColor byuBackgroundColor];
> ```

What does this do? Also, what do the applyBYUFormatting below do? If they aren't doing anything important, let's remove them

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 66 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4jp8yW6Bw8erz4dNQ:-Kc4jp8yW6Bw8erz4dNR:b-y7gtzq) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L66)):*
> ```objc
> -(void)viewWillAppear:(BOOL)animated {
>     [super viewWillAppear:animated];
>     NSIndexPath *selected = [self.tableView indexPathForSelectedRow];
> ```

Change to self.tableView.indexPathForSelectedRow

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4jzbd_62lmZFm0zjS:-Kc4jzbeeYO_-DTnGqJS:b-xo7t46) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L70)):*
> ```objc
>         [self.tableView deselectRowAtIndexPath:selected animated:YES];
>         if (self.currentResponder != nil) {
>             [self.currentResponder becomeFirstResponder];
> ```

What does this line do?

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4kO_yD2TZomfyWY3a:-Kc4kO_yD2TZomfyWY3b:b3efmrh) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L101)):*
> ```objc
> 
> -(NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
>     if (section == 0) {
> ```

Use ternary

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 111 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4ka3Gyelf-d8fTQka:-Kc4ka3Gyelf-d8fTQkb:b-r5pql5) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L111)):*
> ```objc
>     
>     PersonDirectoryPerson *person = self.directory[indexPath.row];
>     cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
> ```

Can you do this in the storyboard?

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 201 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4lH_3bTq3foS51Mrd:-Kc4lH_3bTq3foS51Mre:b-5cynrp) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L201)):*
> ```objc
>     UIBarButtonItem *flexibleItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFlexibleSpace target:self action:nil];
>     
>     if (self.searchEngine.selectedSegmentIndex == 3) {
> ```

#define this one

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 230 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4lj0s1MsIZuAHMAL4:-Kc4lj0t9qHckNI8oj0S:b-b4g167) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ebaf39e1dfc8942a304e0492f859c36c6afd6365/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L230)):*
> ```objc
>     [self hideKeyboard:nil];
>     //Initiate a search when doing reverse search
>     if (self.searchEngine.selectedSegmentIndex == 3) {
> ```

Use the #define

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 303 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4mJkPlTUIv1KBszdH:-Kc4mJkPlTUIv1KBszdI:b-367uh4) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ebaf39e1dfc8942a304e0492f859c36c6afd6365/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L303)):*
> ```objc
> 
> -(void)loadNextPage {
>     [self.spinner startAnimating];
> ```

We never fixed the spinner issue...

---

*[byuSuite/Apps/PersonDirectory/model/PersonDirectoryClient.m, line 24 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4mR5efip8XVXufhnW:-Kc4mR5efip8XVXufhnX:b7r5xui) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ebaf39e1dfc8942a304e0492f859c36c6afd6365/byuSuite/Apps/PersonDirectory/model/PersonDirectoryClient.m#L24)):*
> ```objc
>                                  modifier:(NSString *)modifier
>                               andCallBack:(void (^)(NSArray<PersonDirectoryPerson *> *, int, ByuError *))callback {
>     NSString *pattern = [NSString stringWithFormat:@"%@*", searchPattern];
> ```

Comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93)*

**Comment by ecbrady** [comment]
Review status: 4 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[byuSuite/BYUMobileAppManifest.json, line 540 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4jWh1KF3g1wk3O2vD:-Kc4nhfIkbLqa15RlFfI:b-nudv8p) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/BYUMobileAppManifest.json#L540)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Was this the last one using iPad storyboards in the manifest?
</blockquote></details>

I think it is. But you may want to double check that.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 58 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4jgNKLXE10GmFiwHR:-Kc4pQQe_2ml5y6Ukzj1:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L58)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What does this do? Also, what do the applyBYUFormatting below do? If they aren't doing anything important, let's remove them
</blockquote></details>

Done.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 66 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4jp8yW6Bw8erz4dNQ:-Kc4pcYYdcDxmkVBQuWU:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L66)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Change to self.tableView.indexPathForSelectedRow
</blockquote></details>

Done.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4jzbd_62lmZFm0zjS:-Kc4pdNJdOpKJdijc6xV:bk6u6nx) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L70)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What does this line do?
</blockquote></details>

Acts as if the user has tapped in that text field so that the field is selected and the keyboard is ready.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4kO_yD2TZomfyWY3a:-Kc4q6rmm8SG74AscOYi:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L101)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use ternary
</blockquote></details>

Done.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 111 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4ka3Gyelf-d8fTQka:-Kc4qjqtlyxYfqk2Dtyz:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L111)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can you do this in the storyboard?
</blockquote></details>

Done.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 201 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4lH_3bTq3foS51Mrd:-Kc4nrxCsTdUWGlA8DrG:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L201)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

#define this one
</blockquote></details>

Done.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 230 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4lj0s1MsIZuAHMAL4:-Kc4nspDLLKOAqFyLkdF:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ebaf39e1dfc8942a304e0492f859c36c6afd6365/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L230)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use the #define
</blockquote></details>

Done.

---

*[byuSuite/Apps/PersonDirectory/model/PersonDirectoryClient.m, line 24 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4mR5efip8XVXufhnW:-Kc4o8SeteBetAorO8Au:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ebaf39e1dfc8942a304e0492f859c36c6afd6365/byuSuite/Apps/PersonDirectory/model/PersonDirectoryClient.m#L24)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[byuSuite/BYUMobileAppManifest.json, line 540 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4jWh1KF3g1wk3O2vD:-Kc50u5CAjue4hzY5wER:by4d3x2) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/BYUMobileAppManifest.json#L540)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

I think it is. But you may want to double check that.
</blockquote></details>

Could you put a TODO in the Feature.h saying that we can remove iPad storyboard from the feature?

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4jzbd_62lmZFm0zjS:-Kc4yARO_ltwNZ1qIpWs:b-3yxnax) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L70)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Acts as if the user has tapped in that text field so that the field is selected and the keyboard is ready.
</blockquote></details>

How is the currentResponder determined?

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 107 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4yLy4jXA1kkhoKJ67:-Kc4yLy4jXA1kkhoKJ68:b-pb44rm) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/b3e4df81ea8588cb4a0fc2efe1bd74037b324d2e/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L107)):*
> ```objc
>     PersonDirectoryPerson *person = self.directory[indexPath.row];
>     NSString *text = person.sortName;
>     cell.textLabel.text = text;
> ```

inline

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 205 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4yqeeZq6EX3bUzXwl:-Kc4yqefhPLkZ-C3XQ1i:b-x2genf) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/b3e4df81ea8588cb4a0fc2efe1bd74037b324d2e/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L205)):*
> ```objc
>     textField.inputAccessoryView = toolbar;
>     
>     self.nextButton.enabled = (textField == self.lastName && self.searchEngine.selectedSegmentIndex < REVERSE_SEARCH);  //Disable NEXT button for reverse earch
> ```

Wait... Do we reuse self.lastName for the phone number as well?? If so, let's rename them to textField1 and textField2 (especially since we're adding the second text field for hometown search)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93)*

**Comment by ecbrady** [comment]
Review status: 4 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[byuSuite/BYUMobileAppManifest.json, line 540 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4jWh1KF3g1wk3O2vD:-Kc51V6GEnR2LmXwXLqk:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/BYUMobileAppManifest.json#L540)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Could you put a TODO in the Feature.h saying that we can remove iPad storyboard from the feature?
</blockquote></details>

Done.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4jzbd_62lmZFm0zjS:-Kc51cWV6Nkd8qnQIQpN:b8ypqog) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c30479f1d993bd42292b787ea6adccbaf0a04aba/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L70)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

How is the currentResponder determined?
</blockquote></details>

It is whatever they had most recently been typing in when they selected a cell.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 303 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4mJkPlTUIv1KBszdH:-Kc55ozFjjsQ6K3spptR:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ebaf39e1dfc8942a304e0492f859c36c6afd6365/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L303)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

We never fixed the spinner issue...
</blockquote></details>

Done.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 107 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4yLy4jXA1kkhoKJ67:-Kc51pgsM6d79sDkGRXu:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/b3e4df81ea8588cb4a0fc2efe1bd74037b324d2e/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L107)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

inline
</blockquote></details>

Done.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 205 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93#-Kc4yqeeZq6EX3bUzXwl:-Kc52xIr0tlePWS3rDgp:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/b3e4df81ea8588cb4a0fc2efe1bd74037b324d2e/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L205)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Wait... Do we reuse self.lastName for the phone number as well?? If so, let's rename them to textField1 and textField2 (especially since we're adding the second text field for hometown search)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r4.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/93)*

**Pull request merged**
