### PR TITLE
Hotfix/lab computers

### PR DESCRIPTION
**Pull request by nateyj**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/136)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Apps/LabComputers/controller/LabComputersDetailViewController.m, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136#-KgLcY3IsDXyqZOnFYga:-KgLcY3IsDXyqZOnFYgb:b-jxi4gv) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d7a1ea5886537e123d0a998406f656a1cb066080/byuSuite/Apps/LabComputers/controller/LabComputersDetailViewController.m#L57)):*
> ```objc
> #pragma mark - Custom functions
> 
> -(void)initialzieTableViewData {
> ```

type-o

---

*[byuSuite/Apps/LabComputers/controller/LabComputersListViewController.m, line 68 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136#-KgLcy9ekImV2C0M_Vk-:-KgLcy9ekImV2C0M_Vk0:bzaxf6j) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d7a1ea5886537e123d0a998406f656a1cb066080/byuSuite/Apps/LabComputers/controller/LabComputersListViewController.m#L68)):*
> ```objc
> 	
> 	LabComputersLabTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"cell" forIndexPath:indexPath];
>     cell.nameLabel.text = lab.name;
> ```

Put these all in the cell. Just do `cell.lab = lab;` and have the cell handle the UI set up

---

*[byuSuite/Apps/LabComputers/view/LabComputers.storyboard, line 195 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136#-KgLdM4x5dlMthWNrdKx:-KgLdM4x5dlMthWNrdKy:bxzpypn) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d7a1ea5886537e123d0a998406f656a1cb066080/byuSuite/Apps/LabComputers/view/LabComputers.storyboard#L195)):*
> ```XML
>     </scenes>
>     <resources>
>         <image name="AppleLogo" width="32" height="32"/>
> ```

Do you know why AppleLogo shows up here and Windows doesn't? Is it because you just selected Apple and the default to show in the storyboard?

---

*[byuSuite/Apps/LabComputers/view/LabComputersLabTableViewCell.h, line 12 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136#-KgLdeVTvhs-Z81dwKGA:-KgLdeVTvhs-Z81dwKGB:bpfze1u) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d7a1ea5886537e123d0a998406f656a1cb066080/byuSuite/Apps/LabComputers/view/LabComputersLabTableViewCell.h#L12)):*
> ```objc
> 
> @interface LabComputersLabTableViewCell : UITableViewCell
> @property (weak, nonatomic) IBOutlet UILabel *nameLabel;
> ```

Move these into the .m and just have one property called `lab`. See comment above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136)*

**Comment by nateyj** [comment]
Review status: 11 of 16 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[byuSuite/Apps/LabComputers/controller/LabComputersDetailViewController.m, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136#-KgLcY3IsDXyqZOnFYga:-KgPuCyG5wfunFbxGp8P:bcg9q9f) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d7a1ea5886537e123d0a998406f656a1cb066080/byuSuite/Apps/LabComputers/controller/LabComputersDetailViewController.m#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

type-o
</blockquote></details>

Haha dangit. Fixed it

---

*[byuSuite/Apps/LabComputers/controller/LabComputersListViewController.m, line 68 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136#-KgLcy9ekImV2C0M_Vk-:-KgPwVzmHB7YU8PIsPRZ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d7a1ea5886537e123d0a998406f656a1cb066080/byuSuite/Apps/LabComputers/controller/LabComputersListViewController.m#L68)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Put these all in the cell. Just do `cell.lab = lab;` and have the cell handle the UI set up
</blockquote></details>

Done.

---

*[byuSuite/Apps/LabComputers/view/LabComputers.storyboard, line 195 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136#-KgLdM4x5dlMthWNrdKx:-KgPwqjai0l-cxgp1J_8:by4zq7m) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d7a1ea5886537e123d0a998406f656a1cb066080/byuSuite/Apps/LabComputers/view/LabComputers.storyboard#L195)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do you know why AppleLogo shows up here and Windows doesn't? Is it because you just selected Apple and the default to show in the storyboard?
</blockquote></details>

Yes, that's correct. I just wanted to see what it would like like when I was sizing the image. Want me to remove it?

---

*[byuSuite/Apps/LabComputers/view/LabComputersLabTableViewCell.h, line 12 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136#-KgLdeVTvhs-Z81dwKGA:-KgPxMcQKqI8GeVgUpXB:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d7a1ea5886537e123d0a998406f656a1cb066080/byuSuite/Apps/LabComputers/view/LabComputersLabTableViewCell.h#L12)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Move these into the .m and just have one property called `lab`. See comment above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136#-KgPztdb28J4jwf9YQ34:-KgPztdb28J4jwf9YQ35:b-1z7va2) (no related file):*
Fix constraints

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136)*

**Comment by nateyj** [comment]
Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136#-KgPztdb28J4jwf9YQ34:-KgQ1rtaSv_6rGZ4z0cX:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Fix constraints
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/136)*

**Pull request merged**
