### PR TITLE
hotfix/myNextClass

### PR DESCRIPTION
**Pull request by ghost**
I have yet to rename the folder to MyNextClass instead of My Next Class and add view and controller folders. I also still have to organize the code and add #pragma marks. I hope that waiting to do those things makes it easier to see my changes to the code

---

This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/20)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/My Next Class/MyNextClassViewController.m, line 425 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20#-KVFUyoIPSwk-Kaet6Le:-KVFUyoJ5ywIxAFO0eu1:b67psu3) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/6ef1ed9f33b43f58132fdb63acc045afb98f0c92/byuSuite/Apps/My Next Class/MyNextClassViewController.m#L425)):*
> ```objc
> 
> -(void)loadBuilding {
>     [CampusLocationsClient loadCampusBuildingsWithCallback:^(NSArray<CampusBuilding *> *campusBuildings, ByuError *error) {
> ```

Do we ever reload? If so, we should start the spinner animating before this line as well

---

*[byuSuite/Apps/My Next Class/MyNextClassViewController.m, line 446 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20#-KVFV4T_MyD3y0DDf4Bz:-KVFV4T_MyD3y0DDf4C-:b-pdeqgn) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/6ef1ed9f33b43f58132fdb63acc045afb98f0c92/byuSuite/Apps/My Next Class/MyNextClassViewController.m#L446)):*
> ```objc
>             
>             [self.map addAnnotation:self.building];
>             self.mapLoaded = YES;
> ```

We might be able to replace this with a simple check to see if the map is not null

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20)*

**Comment by nateyj** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/My Next Class/MyNextClassViewController.m, line 425 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20#-KVFUyoIPSwk-Kaet6Le:-KVVMqnjzhxOWA35_pNx:bb7f2mf) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/6ef1ed9f33b43f58132fdb63acc045afb98f0c92/byuSuite/Apps/My Next Class/MyNextClassViewController.m#L425)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Do we ever reload? If so, we should start the spinner animating before this line as well
</details>
done

---

*[byuSuite/Apps/My Next Class/MyNextClassViewController.m, line 446 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20#-KVFV4T_MyD3y0DDf4Bz:-KVVOG3bcaFxvdFpRbNE:beoltuu) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/6ef1ed9f33b43f58132fdb63acc045afb98f0c92/byuSuite/Apps/My Next Class/MyNextClassViewController.m#L446)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> We might be able to replace this with a simple check to see if the map is not null
</details>
In the old code in refreshVeiw(), mapLoaded was set to YES after the request was initiated to get all buildings (which would then add a building annotation to the map upon a successful request). It seems as if the mapLoaded is to help with the timing of requesting the buildings with the other requests. Requesting the building info isn't initiated until the current semester is loaded and the student's schedule is loaded. Let me know when you have a sec and we can look at together

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20#-KVVR1sXVFNkTynf3MTz:-KVVR1sXVFNkTynf3MU-:bv1msdt) (no related file):*
Format code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20)*

**Comment by nateyj** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20#-KVVR1sXVFNkTynf3MTz:-KVVaasAUGBm2c5haZqm:bb7f2mf) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Format code
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20)*

**Comment by nateyj** [comment]
ok

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20#-:-KVVagV8wWw_sCBmyd1z:b32wtd)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20#-KVVR1sXVFNkTynf3MTz:-KVVbOtf8toG1w_o7VCv:bvz73hl) (no related file):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary>
> done
</details>
Remove spaces from group and directory

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20)*

**Comment by romrell4** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20)*

**Comment by nateyj** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20#-KVVR1sXVFNkTynf3MTz:-KVVdM753JVt2f1fB8rn:bb7f2mf) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Remove spaces from group and directory
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/20)*

**Pull request merged**
