### PR TITLE
Hotfix/remove byu web view

### PR DESCRIPTION
**Pull request by nateyj**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/68)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 29 of 30 files at r1.
Review status: 28 of 29 files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/CampusShuttles/controller/CampusShuttlesViewController.m, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/68#-KbBRRIChv4qZvEZDkUa:-KbBRRIChv4qZvEZDkUb:b-m3tldf) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/96e7b10f6d1b6b11239c9c9dc0e193eaa82f19fd/byuSuite/Apps/CampusShuttles/controller/CampusShuttlesViewController.m#L20)):*
> ```objc
>     
>     /*
>      TODO: Because the URL uses http:// we get the warning
> ```

After learning suite is done, can you give yourself a note to look into this one? I don't want this TODO hanging around too long, but I feel bad keeping you off learning suite for so long

---

*[byuSuite/Apps/VolunteerHours/controller/VolunteerHoursViewController.m, line 27 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/68#-KbBSH9BxhvX0teqmEe7:-KbBSH9BxhvX0teqmEe8:b-nm06rh) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/96e7b10f6d1b6b11239c9c9dc0e193eaa82f19fd/byuSuite/Apps/VolunteerHours/controller/VolunteerHoursViewController.m#L27)):*
> ```objc
> 
> 
> #pragma mark - UIWebViewDelegate callbacks
> ```

Check into putting this into the ByuWebViewController code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/68)*

**Comment by romrell4** [comment]
Reviewed 1 of 30 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/68)*

**Comment by nateyj** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/CampusShuttles/controller/CampusShuttlesViewController.m, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/68#-KbBRRIChv4qZvEZDkUa:-KbGFgPzrBk25qwEkePq:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/96e7b10f6d1b6b11239c9c9dc0e193eaa82f19fd/byuSuite/Apps/CampusShuttles/controller/CampusShuttlesViewController.m#L20)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

After learning suite is done, can you give yourself a note to look into this one? I don't want this TODO hanging around too long, but I feel bad keeping you off learning suite for so long
</blockquote></details>

Done.

---

*[byuSuite/Apps/VolunteerHours/controller/VolunteerHoursViewController.m, line 27 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/68#-KbBSH9BxhvX0teqmEe7:-KbGFeL6kItP3ZkKx-3A:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/96e7b10f6d1b6b11239c9c9dc0e193eaa82f19fd/byuSuite/Apps/VolunteerHours/controller/VolunteerHoursViewController.m#L27)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Check into putting this into the ByuWebViewController code
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/68)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/68)*

**Pull request merged**
