### PR TITLE
Hotfix/calendars swift

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/169)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.swift, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP4bnfdXxgtCWkV-zH:-KjP4bnfdXxgtCWkV-zI:b-nlhm0w) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.swift#L23)):*
> ```Swift
>         super.viewDidLoad()
>         
>         tableView.estimatedRowHeight = 44.0                 //Arbitrary value, set to default cell height
> ```

Create extension

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.swift, line 87 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP5n5BMZBqp4BBaMnF:-KjP5n5BMZBqp4BBaMnG:b-pvihsz) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.swift#L87)):*
> ```Swift
>                     //When user allows the feature to access their calendar.
>                     event.calendar = store.defaultCalendarForNewEvents
>                     let controller = EKEventEditViewController()
> ```

Check constructor

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift, line 78 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP4SlNfu7fDE5PIk_F:-KjP4SlNfu7fDE5PIk_G:bpdnpv8) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift#L78)):*
> ```Swift
>     //MARK: Custom Methods
>     
>     private func loadEvents(startDate: Date, months: Int) {
> ```

make month default

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift, line 79 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP3nKA-7UZ-AocKeqh:-KjP3nKA-7UZ-AocKeqi:bcw2w9l) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift#L79)):*
> ```Swift
>     
>     private func loadEvents(startDate: Date, months: Int) {
>         let dateFormat = DateFormatter.defaultDateFormat("YYYY-MM-dd")
> ```

private let

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift, line 89 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP4Mr3vb0oq_itBCcv:-KjP4Mr3vb0oq_itBCcw:b-41yhll) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift#L89)):*
> ```Swift
>                         //Sort just the events coming back. Because we know this small back are within a set date range it will not put self.events out of order since we sort by date.
>                         //Default to today's date just to prevent crashing but will likely never come back as nil
>                         let sortedEvents = events.sorted { return $0.startTime ?? Date()  < $1.startTime ?? Date()  }
> ```

look at inlining

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.swift, line 16 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP-HDWZc7vrWpP6yah:-KjP-HDWZc7vrWpP6yai:b8xet4h) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsViewController.swift#L16)):*
> ```Swift
> class CalendarsViewController: ByuViewController2 , UITableViewDataSource {
>     
>     @IBOutlet private weak var tableView: UITableView!
> ```

Add //MARK

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.swift, line 68 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP-ib4KncgD_I6-X2T:-KjP-ib4KncgD_I6-X2U:bv8z9yn) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsViewController.swift#L68)):*
> ```Swift
>         CalendarsClient.getCalendarCategories { (categories, error) in
>             self.spinner.stopAnimating()
>             if let err = error {
> ```

Flop these

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.swift, line 73 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP-oQ3jVH97ol65UgX:-KjP-oQ3jVH97ol65UgY:b-owpvgv) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsViewController.swift#L73)):*
> ```Swift
>                 var tempCategories = categories ?? [CalendarCategory]()
>                 //Add Academic Calendar to Categories
>                 tempCategories.append(CalendarCategory(dict: ["CategoryId": ACADEMIC_CAL_ID, "Name": ACADEMIC_CAL_NAME]))
> ```

Save the Dictionary as a private static final

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.swift, line 75 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP-wg6C1aZcMd1waNP:-KjP-wg6C1aZcMd1waNQ:br93f9i) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsViewController.swift#L75)):*
> ```Swift
>                 tempCategories.append(CalendarCategory(dict: ["CategoryId": ACADEMIC_CAL_ID, "Name": ACADEMIC_CAL_NAME]))
>                 //Sort Categories alphabetically by name
>                 tempCategories.sort { return $0.name ?? "" < $1.name ?? "" }
> ```

Check if default is needed

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.swift, line 75 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP00wcuLy9SpzBv_tJ:-KjP00wcuLy9SpzBv_tK:b-cxex32) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsViewController.swift#L75)):*
> ```Swift
>                 tempCategories.append(CalendarCategory(dict: ["CategoryId": ACADEMIC_CAL_ID, "Name": ACADEMIC_CAL_NAME]))
>                 //Sort Categories alphabetically by name
>                 tempCategories.sort { return $0.name ?? "" < $1.name ?? "" }
> ```

Instead of using sort, use sorted, and just set the self.calendarCategories

---

*[byuSuite/Apps/Calendars/model/CalendarCategory.swift, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP0RNCB2WgTJo9k0DO:-KjP0RNCB2WgTJo9k0DP:b-pb44rm) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarCategory.swift#L20)):*
> ```Swift
>     init(dict: [String: Any]) {
>         categoryId = dict["CategoryId"] as? String
>         let temp = dict["Name"] as? String
> ```

inline

---

*[byuSuite/Apps/Calendars/model/CalendarCategory.swift, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP0Vox5b_Thy-CjWjN:-KjP0Vox5b_Thy-CjWjO:bclgm3v) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarCategory.swift#L23)):*
> ```Swift
>         name = temp?.decodedHTMLEntities()
>         if let categoryId = categoryId {
>             iCalFeed = String(format: "%@%@", I_CAL_FEED_BASE_URL, categoryId)
> ```

Use regular swift notation. Talk to me about this one

---

*[byuSuite/Apps/Calendars/model/CalendarEvent.swift, line 13 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP1AXXOnFHyvN65WsN:-KjP1AXXOnFHyvN65WsO:b7jle9y) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarEvent.swift#L13)):*
> ```Swift
> 
> private let DATE_FORMAT = DateFormatter.defaultDateFormat("yyyy-MM-dd HH:mm:ss")
> private let STRING_DATE_FORMAT = DateFormatter.defaultDateFormat("MM/dd/YYYY hh:mm a")
> ```

Use lower case Y

---

*[byuSuite/Apps/Calendars/model/CalendarEvent.swift, line 64 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP2SZ1vxVcxV0ue1z1:-KjP2SZ1vxVcxV0ue1z2:behkl6x) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarEvent.swift#L64)):*
> ```Swift
>     func generateEkEvent(store: EKEventStore) -> EKEvent? {
>         guard let eventTitle = title,
>             let startDate = startTime,
> ```

Double check if these are required

---

*[byuSuite/Apps/Calendars/model/CalendarEvent.swift, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP2Wsl2aiV6Z4fBJpY:-KjP2Wsl2aiV6Z4fBJpZ:b-ui2ghd) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarEvent.swift#L77)):*
> ```Swift
>         
>         if event.startDate == event.endDate {
>             event.endDate = event.endDate.addingTimeInterval(1.0)   //Add one second to avoid bug in EKEventEditViewController
> ```

Test to see if this is still a bug

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.swift, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP2nMOVTI0ZHgTSekK:-KjP2nMOVTI0ZHgTSekL:b-pb44rm) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarsClient.swift#L18)):*
> ```Swift
>         request.startAsynchronous { (response) in
>             if response.succeeded, let dataArray = response.getDataJson() as? [[String: Any]] {
>                 let categories = dataArray.map({ (dict) -> CalendarCategory in
> ```

inline

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.swift, line 35 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP2eDC7m8hlR1RNmZ0:-KjP2eDC7m8hlR1RNmZ1:bmxanqw) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarsClient.swift#L35)):*
> ```Swift
>                 completionHandler(nil, response.error)
>             } else {
>                 guard let result = response.getDataJson() as? [[String: Any]] else {
> ```

Flop this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169)*

**Comment by ecbrady** [comment]
Review status: 14 of 22 files reviewed at latest revision, 17 unresolved discussions.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.swift, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP4bnfdXxgtCWkV-zH:-KjPLcY8HdUCP7pGZLvl:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.swift#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Create extension
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.swift, line 87 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP5n5BMZBqp4BBaMnF:-KjPM12ug-IHRRWcBfOm:b-xx0vvp) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.swift#L87)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Check constructor
</blockquote></details>

There doesn't seem to be a constructor that takes parameters.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift, line 78 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP4SlNfu7fDE5PIk_F:-KjPMC7YDwHUrjg0U6NK:b-xifytr) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift#L78)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

make month default
</blockquote></details>

Should I not worry about passing in months then, when I call this method?

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift, line 79 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP3nKA-7UZ-AocKeqh:-KjPMUGmXWwkqiHbsjDR:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift#L79)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

private let
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift, line 89 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP4Mr3vb0oq_itBCcv:-KjPMrQxSGsZwZE_hbvx:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift#L89)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

look at inlining
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.swift, line 16 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP-HDWZc7vrWpP6yah:-KjPN8Do2uczwkRZPRYX:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsViewController.swift#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add //MARK
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.swift, line 68 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP-ib4KncgD_I6-X2T:-KjPNqHXTU89xJzWBwP-:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsViewController.swift#L68)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Flop these
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.swift, line 73 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP-oQ3jVH97ol65UgX:-KjPONTfuKEYAMv8cDWf:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsViewController.swift#L73)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Save the Dictionary as a private static final
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.swift, line 75 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP-wg6C1aZcMd1waNP:-KjPOO-07_5QML_63DyJ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsViewController.swift#L75)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Check if default is needed
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.swift, line 75 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP00wcuLy9SpzBv_tJ:-KjPOe2wwVCyQIj-v8bg:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsViewController.swift#L75)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Instead of using sort, use sorted, and just set the self.calendarCategories
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/model/CalendarCategory.swift, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP0RNCB2WgTJo9k0DO:-KjPOqzdTiU9Qi1bIWbB:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarCategory.swift#L20)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

inline
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/model/CalendarCategory.swift, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP0Vox5b_Thy-CjWjN:-KjPPGA0MiEkIUsMUpK9:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarCategory.swift#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use regular swift notation. Talk to me about this one
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/model/CalendarEvent.swift, line 13 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP1AXXOnFHyvN65WsN:-KjPPN6_uMZasUhMocJY:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarEvent.swift#L13)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use lower case Y
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/model/CalendarEvent.swift, line 64 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP2SZ1vxVcxV0ue1z1:-KjPPZ-1ZaRAocQTLW_S:b-22wora) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarEvent.swift#L64)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Double check if these are required
</blockquote></details>

They are indeed.

---

*[byuSuite/Apps/Calendars/model/CalendarEvent.swift, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP2Wsl2aiV6Z4fBJpY:-KjPPztIOM96liQ8APm_:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarEvent.swift#L77)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Test to see if this is still a bug
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.swift, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP2nMOVTI0ZHgTSekK:-KjPQDp0cVB0-u3pNmGN:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarsClient.swift#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

inline
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.swift, line 35 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP2eDC7m8hlR1RNmZ0:-KjPQg9twpv5UL71ouPc:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/model/CalendarsClient.swift#L35)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Flop this one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169)*

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift, line 78 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP4SlNfu7fDE5PIk_F:-KjPRI38cvioiVAKnYkv:bls7g58) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift#L78)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Should I not worry about passing in months then, when I call this method?
</blockquote></details>

Yup. Don't pass it in

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjPS9YymKDtXkicFLw6:-KjPS9YymKDtXkicFLw7:bj71q5a) (no related file):*
Look into search with me

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift, line 78 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjP4SlNfu7fDE5PIk_F:-KjczKHdXMpcQhkj9hOb:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e9e513ef9666fd5ffdfe8da38fcfe86ac3e898a5/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.swift#L78)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Yup. Don't pass it in
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169)*

**Comment by ecbrady** [comment]
Review status: 19 of 24 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjPS9YymKDtXkicFLw6:-KjdE5T5mHbh9nb3I1GS:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Look into search with me
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/Reusable/UI/ByuSearchViewController.swift, line 11 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjdH4YkL8ZC7dx2YBie:-KjdH4YkL8ZC7dx2YBif:b-xhxpi9) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d578066c19175ff8455ff89a51009e56ea3ae4d1/byuSuite/Classes/Reusable/UI/ByuSearchViewController.swift#L11)):*
> ```Swift
> import UIKit
> 
> //TODO: Read and verify comments
> ```

Resolve TODO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169)*

**Comment by ecbrady** [comment]
Review status: 23 of 24 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/Reusable/UI/ByuSearchViewController.swift, line 11 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169#-KjdH4YkL8ZC7dx2YBie:-KjdT_oS9lG4xEdvsrxU:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d578066c19175ff8455ff89a51009e56ea3ae4d1/byuSuite/Classes/Reusable/UI/ByuSearchViewController.swift#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Resolve TODO
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/169)*

**Pull request merged**
