### PR TITLE
MyNextClass Refactor

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/67)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxVsIi40ES_UpQqD4C:-KaxVsIi40ES_UpQqD4D:bqd95f) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/3a3e7f755a20b0b65e05c7c367c229bd50f79094/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L101)):*
> ```objc
>     if (indexPath.section == 0) {
>         if (indexPath.row == 0) {
>             cell.detailTextLabel.text = self.nextClassInTable;
> ```

If there are all different cells, we can just put the text in the storyboard

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 108 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxVhL3jzHqJV_W3B_V:-KaxVhL4-z3m8Mi5x5lo:bray6x0) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/3a3e7f755a20b0b65e05c7c367c229bd50f79094/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L108)):*
> ```objc
>         }
>     } else if (indexPath.section == 1) {
>         cell.textLabel.numberOfLines = 0;
> ```

What happens when you remove this? I think we can actually add this to the storyboard

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxWcUEV8c0N1cysEnJ:-KaxWcUEV8c0N1cysEnK:bqms8zg) (no related file):*
Issue with scrolling. Try on a small phone. The tableView auto-refreshes whenever you hit the bottom

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxWi3UySMcJPogP54u:-KaxWi3UySMcJPogP54v:b-a2mmaa) (no related file):*
The top section should probably have something in it... Either that or we should remove it?

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 125 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxWxsnpay2svYHtLR1:-KaxWxsnpay2svYHtLR2:b-w3b4tz) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/3a3e7f755a20b0b65e05c7c367c229bd50f79094/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L125)):*
> ```objc
>     if (indexPath.section == 0) {
>         if (indexPath.row == 0) {
>             NSString *urlString = [NSString stringWithFormat:@"byuSuite://learningSuite/%@", [self.nextClass.course stringByAddingPercentEscapesUsingEncoding:NSASCIIStringEncoding]];
> ```

Oh wow! I didn't know that we were doing it like this! There might be an easier way... Talk to me about this one (and the one below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxXCP2jjVHG96SfUWH:-KaxXCP2jjVHG96SfUWI:bvm4c1g) (no related file):*
The time is getting truncated. We should figure out a better way of displaying the date stuff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67)*

**Comment by ecbrady** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxWi3UySMcJPogP54u:-Kaxgy7Bgej6sxz0xAZR:byg433c) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

The top section should probably have something in it... Either that or we should remove it?
</blockquote></details>

Refactored.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxWcUEV8c0N1cysEnJ:-KaxgzIvs082ybnXdGtA:bt2vr1b) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Issue with scrolling. Try on a small phone. The tableView auto-refreshes whenever you hit the bottom
</blockquote></details>

Fixed.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxVsIi40ES_UpQqD4C:-KaxdXWwc0vWVU8SQvzv:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/3a3e7f755a20b0b65e05c7c367c229bd50f79094/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L101)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

If there are all different cells, we can just put the text in the storyboard
</blockquote></details>

Done.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 108 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxVhL3jzHqJV_W3B_V:-Kaxdz8pYGIPNnteMPao:b-r07wrh) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/3a3e7f755a20b0b65e05c7c367c229bd50f79094/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L108)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What happens when you remove this? I think we can actually add this to the storyboard
</blockquote></details>

So it does have to be set to 0 but I moved it to the storyboard.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxVsIi40ES_UpQqD4C:-KaxhoeI8twOH7sF9Cji:b-qs8y02) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/3a3e7f755a20b0b65e05c7c367c229bd50f79094/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L101)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do what we talked about

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 84 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxhXU9Jj8pBDnmbeTM:-KaxhXU9Jj8pBDnmbeTN:byp18fd) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/784352eddf8f759573988453ebbe56187879f217/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L84)):*
> ```objc
> #pragma mark - UITableViewDataSource and Delegate functions
> 
> -(NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
> ```

Remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxXCP2jjVHG96SfUWH:-KbB2qo2knrpzCFp9vW-:ba6dw8v) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

The time is getting truncated. We should figure out a better way of displaying the date stuff
</blockquote></details>

Done. Counts in hours now instead of days.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxVsIi40ES_UpQqD4C:-KaxmlYhW7p2cmGNFr3o:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/3a3e7f755a20b0b65e05c7c367c229bd50f79094/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L101)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do what we talked about
</blockquote></details>

Done.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 125 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxWxsnpay2svYHtLR1:-KbB6pKvfW9O0WrUFwSL:bvayom) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/3a3e7f755a20b0b65e05c7c367c229bd50f79094/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L125)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Oh wow! I didn't know that we were doing it like this! There might be an easier way... Talk to me about this one (and the one below)
</blockquote></details>

Simplified a little.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 84 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KaxhXU9Jj8pBDnmbeTM:-KaxiDV0ZUy3GrsH0Qrs:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/784352eddf8f759573988453ebbe56187879f217/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L84)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 87 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KbB8g_WRni2zceSk70q:-KbB8g_X7S39woQcShZZ:b-2rufmy) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/19414f400c92b3c61297de17957b89119388e03e/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L87)):*
> ```objc
>     
>     if (indexPath.row != 3) {
>         cell.detailTextLabel.text = self.tableData[indexPath.row][@"detailText"];
> ```

Try to remove the if statement with @"" or [NSNull null]

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 99 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KbB8oGOTm2Tpffzs7rG:-KbB8oGOTm2Tpffzs7rH:bwpp5dn) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/19414f400c92b3c61297de17957b89119388e03e/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L99)):*
> ```objc
> -(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
>     if (indexPath.row == 0) {
>         //Open Learning Suite via the byuSuiteAppDelegate
> ```

add the function name to this comment too (handleOpenURL or something like that)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 346 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KbB9GL7P-At4RAY5nyM:-KbB9GL7P-At4RAY5nyN:bbdscg9) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/19414f400c92b3c61297de17957b89119388e03e/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L346)):*
> ```objc
>                 CampusBuilding *building = value;
>                 
>                 if ([building.building isEqualToString:self.nextClass.building]) {
> ```

Replace this with just a return statement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 87 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KbB8g_WRni2zceSk70q:-KbB91PgnI0tDwCOQ-Kw:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/19414f400c92b3c61297de17957b89119388e03e/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L87)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Try to remove the if statement with @"" or [NSNull null]
</blockquote></details>

Done.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 99 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KbB8oGOTm2Tpffzs7rG:-KbB9Nwmd_iYJt7uR1JP:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/19414f400c92b3c61297de17957b89119388e03e/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L99)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

add the function name to this comment too (handleOpenURL or something like that)
</blockquote></details>

Done.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 346 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-KbB9GL7P-At4RAY5nyM:-KbB9f7jPSZJpcK_Qf7K:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/19414f400c92b3c61297de17957b89119388e03e/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L346)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Replace this with just a return statement
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/67#-:-KbBA3GY0hqiG8S8m4ps:bnfp4nl)*

**Pull request merged**
