### PR TITLE
Fix space bug fix

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/51)

### CODE REVIEW

**Comment by ecbrady** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/51#-KZ7GHWb7wBWfbomQ1IW:-KZ7GHWb7wBWfbomQ1IX:brwg7l2) (no related file):*
I hope you don't mind, I ran the formatter on parking as well and fixed a few small things in here for that. The main bug fix is the extra line in AddVehicleViewController.m. I don't know if that was the best way to do it but I tested it and it works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/51)*

**Comment by romrell4** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/Parking/controller/AddVehicleViewController.m, line 110 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/51#-KZ9MDeLS6dtYqn8aBGM:-KZ9MDeLS6dtYqn8aBGN:byr5w9v) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/f46833dfb807250bc94e8ac1ea995ecf9fdf0f80/byuSuite/Apps/Parking/controller/AddVehicleViewController.m#L110)):*
> ```objc
> 	
> 	textField.text = [textField.text stringByReplacingCharactersInRange:range withString:[string uppercaseString]];
>     textField.text = [textField.text stringByReplacingOccurrencesOfString:@" " withString:@""];
> ```

Great. Let's just add a comment explaining both of these lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/51)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/Parking/controller/AddVehicleViewController.m, line 110 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/51#-KZ9MDeLS6dtYqn8aBGM:-KZNDYQCSROjxmRXDnS8:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/f46833dfb807250bc94e8ac1ea995ecf9fdf0f80/byuSuite/Apps/Parking/controller/AddVehicleViewController.m#L110)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Great. Let's just add a comment explaining both of these lines
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/51)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/51)*

**Pull request merged**
