### PR TITLE
Hotfix/control dates

### PR DESCRIPTION
**Pull request by nateyj**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/60)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 54 of 54 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m, line 168 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaNq_jNVd_E4kDI9Yh6:-KaNq_jNVd_E4kDI9Yh7:b-qzrxxu) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c2ef789d466dab42db0c997859585520860a14a2/byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m#L168)):*
> ```objc
> -(void)createButtonSucceeded:(SemesterButton *)button {
>     self.navigationItem.rightBarButtonItem.enabled = NO;
>     self.schedule = [ByuStudentSchedule createStudentScheduleWithDelegate:self];
> ```

By replacing this, you should actually be able to remove the callback methods as well.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaNqsyqerS_jyHcRrhO:-KaNqsyryVl_S_SKgHf2:b-ow2bg) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bc400cd66ad88fe9af0f030d621de1bd4fce294b/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L70)):*
> ```objc
> 
> //object = ByuStudentSchedule
> -(void)createByuCFrameworkServiceObjectFailed:(ByuCFrameworkService *)object {
> ```

I'm confused... have we not refactored this one yet?

---

*[byuSuite/Classes/ByuRequest/ByuRequest.h, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaNraRW4aZgbJ81Y3yO:-KaNraRW4aZgbJ81Y3yP:byp18fd) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bc400cd66ad88fe9af0f030d621de1bd4fce294b/byuSuite/Classes/ByuRequest/ByuRequest.h#L57)):*
> ```objc
>  * @param block     A block of code that processes the request's response JSON data before passing it as an argument to the request's callback
>  */
> +(void)startAsynchronousWithURL:(NSURL *)url callback:(ByuRequestCallback)callback block:(id(^)(id responseData))block;
> ```

Remove

---

*[byuSuite/Classes/ByuRequest/ByuRequest.m, line 84 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaNre6LlY2Z6R9lm9vA:-KaNre6LlY2Z6R9lm9vB:byp18fd) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bc400cd66ad88fe9af0f030d621de1bd4fce294b/byuSuite/Classes/ByuRequest/ByuRequest.m#L84)):*
> ```objc
> }
> 
> +(void)startAsynchronousWithURL:(NSURL *)url callback:(ByuRequestCallback)callback block:(id(^)(id responseData))block {
> ```

Remove

---

*[byuSuite/Classes/ReusableClients/ControlDates/ControlDatesClient.h, line 25 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaNrkgboAnHT8xKV3jV:-KaNrkgboAnHT8xKV3jW:bl507b9) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bc400cd66ad88fe9af0f030d621de1bd4fce294b/byuSuite/Classes/ReusableClients/ControlDates/ControlDatesClient.h#L25)):*
> ```objc
>  * @param callback A callback returning nothing and taking a YearTerm and a ByuError as parameters.
>  */
> +(void)getYearTermWithClassDatesWithYearTerm:(NSString *)yearTerm callback:(YearTermCallback)callback;
> ```

I think we might be able to come up with a better name for this one. What does "WithClassDates" mean here?

---

*[byuSuite/Classes/ReusableClients/ControlDates/YearTerm.m, line 15 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaNs-PMFM6KDVfcXC9q:-KaNs-PMFM6KDVfcXC9r:b-dh3jwj) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bc400cd66ad88fe9af0f030d621de1bd4fce294b/byuSuite/Classes/ReusableClients/ControlDates/YearTerm.m#L15)):*
> ```objc
> @implementation YearTerm
> 
> +(YearTerm *)yearTermWithDictionary:(NSDictionary *)dict {
> ```

We should just have this one call the other one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60)*

**Comment by nateyj** [comment]
Review status: 0 of 53 files reviewed at latest revision, 6 unresolved discussions.

---

*[byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m, line 168 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaNq_jNVd_E4kDI9Yh6:-KaNyjC05hLLE8yrSsRo:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/c2ef789d466dab42db0c997859585520860a14a2/byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m#L168)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

By replacing this, you should actually be able to remove the callback methods as well.
</blockquote></details>

Done.

---

*[byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaNqsyqerS_jyHcRrhO:-KaNtNvbIL5aUGT4d6me:bcqhz2b) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bc400cd66ad88fe9af0f030d621de1bd4fce294b/byuSuite/Apps/MyNextClass/controller/MyNextClassViewController.m#L70)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I'm confused... have we not refactored this one yet?
</blockquote></details>

We have not. I was just trying to replace ByuCurrentYearTerm in this hot fix

---

*[byuSuite/Classes/ByuRequest/ByuRequest.h, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaNraRW4aZgbJ81Y3yO:-KaNvUTc7Nnvf3q-N95O:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bc400cd66ad88fe9af0f030d621de1bd4fce294b/byuSuite/Classes/ByuRequest/ByuRequest.h#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---

*[byuSuite/Classes/ByuRequest/ByuRequest.m, line 84 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaNre6LlY2Z6R9lm9vA:-KaNvVyFibPEaKl8BvK4:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bc400cd66ad88fe9af0f030d621de1bd4fce294b/byuSuite/Classes/ByuRequest/ByuRequest.m#L84)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---

*[byuSuite/Classes/ReusableClients/ControlDates/ControlDatesClient.h, line 25 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaNrkgboAnHT8xKV3jV:-KaNwaqDwVJ0wjp2nlaG:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bc400cd66ad88fe9af0f030d621de1bd4fce294b/byuSuite/Classes/ReusableClients/ControlDates/ControlDatesClient.h#L25)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think we might be able to come up with a better name for this one. What does "WithClassDates" mean here?
</blockquote></details>

Done.

---

*[byuSuite/Classes/ReusableClients/ControlDates/YearTerm.m, line 15 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaNs-PMFM6KDVfcXC9q:-KaNxeEIzkXxwkPTMYdZ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bc400cd66ad88fe9af0f030d621de1bd4fce294b/byuSuite/Classes/ReusableClients/ControlDates/YearTerm.m#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

We should just have this one call the other one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60)*

**Comment by romrell4** [comment]
Reviewed 53 of 54 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/ByuRequest/ByuRequest.h, line 32 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaO-D0qgwn9MmXtMJAV:-KaO-D0qgwn9MmXtMJAW:bilw7y2) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/5339a213d19f72352979ab0658d0fa2958752a47/byuSuite/Classes/ByuRequest/ByuRequest.h#L32)):*
> ```objc
> } MimeType;
> 
> typedef void(^ByuRequestCallback)(id value, ByuError *error);
> ```

Remove this one as well if it's not being used

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60)*

**Comment by nateyj** [comment]
Review status: 50 of 51 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/ByuRequest/ByuRequest.h, line 32 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60#-KaO-D0qgwn9MmXtMJAV:-KaO0mKnh7f_xvWbXLbL:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/5339a213d19f72352979ab0658d0fa2958752a47/byuSuite/Classes/ByuRequest/ByuRequest.h#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove this one as well if it's not being used
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/60)*

**Pull request merged**
