### PR TITLE
Hotfix/map my finals - Identifier removal

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/47)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/47#-KYUWuunSIgxCF99o9IE:-KYUWuunSIgxCF99o9IF:bizauaz) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/b34ac5b2d3d49d99b7263eacd601e1ca6c2408a1/byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m#L23)):*
> ```objc
> @property (nonatomic) ByuCredentialHandler *credentialHandler;
> @property (nonatomic) ByuCurrentYearTerm *currentYearTerm;
> @property (nonatomic) NSArray *finals;
> ```

Give this one a type

---

*[byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m, line 32 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/47#-KYUWxmGrn5Hl-vmzoEH:-KYUWxmGrn5Hl-vmzoEI:b-3ev9wn) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/b34ac5b2d3d49d99b7263eacd601e1ca6c2408a1/byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m#L32)):*
> ```objc
>     self = [super init];
>     if (self) {
>         self.yearTerm = nil;
> ```

Remove this line since it will always be nil right after doing [super init]

---

*[byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/47#-KYUX3LzKCA04b4k-SVk:-KYUX3LzKCA04b4k-SVl:bj88qxg) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/b34ac5b2d3d49d99b7263eacd601e1ca6c2408a1/byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m#L57)):*
> ```objc
>     self.credentialHandler = [ByuCredentialHandler ByuCredentialHandlerWithDelegate:nil];
>     
>     if (self.personId && self.yearTerm) {
> ```

Don't need to check for self.personId anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/47)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m, line 91 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/47#-KYUX8JMwPkcDN4uqmoF:-KYUX8JMwPkcDN4uqmoG:b-mqcl2o) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/b34ac5b2d3d49d99b7263eacd601e1ca6c2408a1/byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m#L91)):*
> ```objc
>     }
>     
>     if (self.yearTerm && self.personId) {
> ```

Don't need to check for personId anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/47)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/47#-KYUWuunSIgxCF99o9IE:-KYUXYpV344AmXJd_UIm:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/b34ac5b2d3d49d99b7263eacd601e1ca6c2408a1/byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Give this one a type
</blockquote></details>

Done.

---

*[byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m, line 32 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/47#-KYUWxmGrn5Hl-vmzoEH:-KYUXZNtoKnaKb7qTFrU:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/b34ac5b2d3d49d99b7263eacd601e1ca6c2408a1/byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove this line since it will always be nil right after doing [super init]
</blockquote></details>

Done.

---

*[byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/47#-KYUX3LzKCA04b4k-SVk:-KYUXnMHSfusifPIWF1D:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/b34ac5b2d3d49d99b7263eacd601e1ca6c2408a1/byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Don't need to check for self.personId anymore
</blockquote></details>

Done.

---

*[byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m, line 91 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/47#-KYUX8JMwPkcDN4uqmoF:-KYUXnw8Jgv2pAj4hBeB:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/b34ac5b2d3d49d99b7263eacd601e1ca6c2408a1/byuSuite/Classes/Basic Data Access/ByuFinalsSchedule/ByuFinalsScheduleRequest.m#L91)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Don't need to check for personId anymore
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/47)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/47)*

**Pull request merged**
