### PR TITLE
Refactor client to remove SOA requests

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/9)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 18 of 18 files at r1.
Review status: 14 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/SickVacation/controller/SickVacationAccrualDetailViewController.h, line 10 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsHUbdW7a8HqaGccXF:-KUsHUbdW7a8HqaGccXG:b2jqal) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationAccrualDetailViewController.h#L10)):*
> ```objc
> 
> #import "ByuViewController.h"
> #import "ByuSickVacationLeaveAccrual.h"
> ```

Sorry, but I actually think that this is better without the Byu. I would only ever use Byu if the object could possibly be a NON byu object (such as Error or Response or Request)

---

*[byuSuite/Apps/SickVacation/controller/SickVacationAccrualDetailViewController.m, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsHpjP9ylEP08uIiY_:-KUsHpjP9ylEP08uIiYa:b64u3xj) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationAccrualDetailViewController.m#L31)):*
> ```objc
>     
>     //Load categories with key/value pairs for each item displayed in SickVacationAccrualDetailViewController
>     self.categories = @[  @{@"key": @"Carried Over:", @"value": [NSString stringWithFormat:@"%d Hours", self.leaveAccrual.hoursCarryover]},
> ```

Instead of duplicating all of these, let's write a simple function that will do that format for us

---

*[byuSuite/Apps/SickVacation/controller/SickVacationDetailViewController.m, line 45 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsI3NP2LT25bOplSQc:-KUsI3NP2LT25bOplSQd:b-1lpnxx) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationDetailViewController.m#L45)):*
> ```objc
> -(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
>     UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"cell"];
>     ByuSickVacationLeaveAccrual *leaveAccrual = [self.leavePlan.leaveAccruals objectAtIndex:indexPath.row];
> ```

Replace objectAtIndex with []

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 38 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsKxKSot9mYK0xeD3j:-KUsKxKSot9mYK0xeD3k:b6xq9od) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L38)):*
> ```objc
>             }];
>         } else {
>             [self.spinner stopAnimating];
> ```

Shouldn't we put this outside the if (error) so that the spinner stops on success or failure

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsM3GG47UIf2JYfYzf:-KUsM3GG47UIf2JYfYzg:b4fp40p) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L39)):*
> ```objc
>         } else {
>             [self.spinner stopAnimating];
>             self.tableView.hidden = NO;
> ```

We might not need to do this...

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 41 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsM8alvnHCNZeZ1AJi:-KUsM8alvnHCNZeZ1AJj:b-zg275z) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L41)):*
> ```objc
>             self.tableView.hidden = NO;
>             //If the plans are not valid, ie. a student (or anybody who does not have sick or vacation leave):
>             if (![self hasValidLeavePlan:leavePlans]) {
> ```

This should probably be an or in the first if statement. if (error || ![self hasValidLeavePlan:leavePlans])... Or is there supposed to be a different error message? If that is the case, make it an else if

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 78 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsKs8rzc-9Gkmztncb:-KUsKs8rzc-9Gkmztncc:b6jrl84) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L78)):*
> ```objc
> }
> 
> -(NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
> ```

Add pragma marks and reorganize code

---

*[byuSuite/Apps/SickVacation/model/ByuSickVacationClient.m, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsN3ixnKsTU7pVCYZc:-KUsN3ixnKsTU7pVCYZd:b-vpn1cr) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/model/ByuSickVacationClient.m#L26)):*
> ```objc
>         } else {
>             NSDictionary *responseDict = [response getDataJson];
>             NSMutableArray<ByuSickVacationLeavePlan *> *leavePlans = [NSMutableArray array];
> ```

We should be able to do a transform here. Anytime you write [NSMutableArray....] think about using a transform or a filter

---

*[byuSuite/Apps/SickVacation/model/ByuSickVacationLeaveAccrual.m, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsNFaYCu58gpBDZ3vG:-KUsNFaYCu58gpBDZ3vH:b-i0upyq) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/model/ByuSickVacationLeaveAccrual.m#L19)):*
> ```objc
>     NSDateFormatter *dateFormater = [[NSDateFormatter alloc] init];
>     [dateFormater setDateFormat:@"yyy-MM-dd"];
>     dateFormater.locale = [NSLocale localeWithLocaleIdentifier:@"en_us"];
> ```

I've never used this before... is it important?

---

*[byuSuite/Apps/SickVacation/model/ByuSickVacationLeavePlan.h, line 10 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsNLG7xpJuzYYXgt5r:-KUsNLG8QDOF7Kpd8QLi:bodj5rx) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/model/ByuSickVacationLeavePlan.h#L10)):*
> ```objc
> 
> #import <Foundation/Foundation.h>
> #import "ByuSickVacationLeaveAccrual.h"
> ```

Change back :)

---

*[byuSuite/Apps/SickVacation/model/ByuSickVacationLeavePlan.m, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsNP1h7cjUH6J4P2zh:-KUsNP1h7cjUH6J4P2zi:b2wgiyv) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/model/ByuSickVacationLeavePlan.m#L18)):*
> ```objc
>     me.planType = [dict nullSafeObjectForKey:@"plan_type"];
>     me.planTypeDescription = [dict nullSafeObjectForKey:@"plan_type_descr"];
>     NSMutableArray<ByuSickVacationLeaveAccrual *> *tempArray = [NSMutableArray array];
> ```

transform

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9)*

**Comment by ecbrady** [comment]
Review status: 1 of 10 files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/SickVacation/controller/SickVacationDetailViewController.m, line 45 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsI3NP2LT25bOplSQc:-KUsY_c5p2B94cEtDFNv:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationDetailViewController.m#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Replace objectAtIndex with []
</details>
Done.

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 38 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsKxKSot9mYK0xeD3j:-KUsWtR0xyAN1MFvLUUe:b2nhktp) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L38)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Shouldn't we put this outside the if (error) so that the spinner stops on success or failure
</details>
OK.

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsM3GG47UIf2JYfYzf:-KUsX61e9yG40l6dvYCr:b-bftx14) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L39)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> We might not need to do this...
</details>
Currently we need to. I think there's something in the Storyboard though that I could change so we dont need to.

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 41 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsM8alvnHCNZeZ1AJi:-KUsXaxxLdfRjfBdlYsn:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L41)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> This should probably be an or in the first if statement. if (error || ![self hasValidLeavePlan:leavePlans])... Or is there supposed to be a different error message? If that is the case, make it an else if
</details>
Done.

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 78 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsKs8rzc-9Gkmztncb:-KUsXlsrS-xWc2dX_HyN:b-d3ko6y) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L78)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Add pragma marks and reorganize code
</details>
Which new pragma marks would you like?

---

*[byuSuite/Apps/SickVacation/model/SickVacationLeavePlan.h, line 10 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsNLG7xpJuzYYXgt5r:-KUsYPKphDkCZDQvNnWV:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/model/SickVacationLeavePlan.h#L10)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Change back :)
</details>
Done.

---

*[byuSuite/Apps/SickVacation/controller/SickVacationAccrualDetailViewController.h, line 10 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsHUbdW7a8HqaGccXF:-KUsR8W8DsDPdpN18-0Y:bojbizx) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationAccrualDetailViewController.h#L10)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Sorry, but I actually think that this is better without the Byu. I would only ever use Byu if the object could possibly be a NON byu object (such as Error or Response or Request)
</details>
Okay. I used Byu since there were already files of the same names. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9)*

**Comment by ecbrady** [comment]
Review status: 1 of 10 files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/SickVacation/controller/SickVacationAccrualDetailViewController.m, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsHpjP9ylEP08uIiY_:-KUscVVPIcmE4YdRLYsf:bz6otn2) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationAccrualDetailViewController.m#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Instead of duplicating all of these, let's write a simple function that will do that format for us
</details>
I'm sure you'll probably want it changed, but something along these lines?

---

*[byuSuite/Apps/SickVacation/model/SickVacationClient.m, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsN3ixnKsTU7pVCYZc:-KUseHP0HJVQjKEjHLEm:blop2j7) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/model/SickVacationClient.m#L26)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> We should be able to do a transform here. Anytime you write [NSMutableArray....] think about using a transform or a filter
</details>
How would I do that with the JSON data saved into a dictionary and not an array?

---

*[byuSuite/Apps/SickVacation/model/SickVacationLeavePlan.m, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsNP1h7cjUH6J4P2zh:-KUsf3aFWPfUma_Q3eVq:b-wnirzl) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/model/SickVacationLeavePlan.m#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> transform
</details>
This seems to work but is it right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9)*

**Comment by ecbrady** [comment]
Review status: 0 of 10 files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/SickVacation/model/SickVacationLeaveAccrual.m, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsNFaYCu58gpBDZ3vG:-KUsfcTUIQO997i3OcoJ:bshjslh) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/model/SickVacationLeaveAccrual.m#L19)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> I've never used this before... is it important?
</details>
It appears not to be...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9)*

**Comment by ecbrady** [comment]
Review status: 0 of 10 files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 78 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsKs8rzc-9Gkmztncb:-KUsj-Mtf1XEW72UqEyo:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L78)):*
<details><summary><i>Previously, ecbrady wrote…</i></summary>
> Which new pragma marks would you like?
</details>
Done.

---

*[byuSuite/Apps/SickVacation/model/SickVacationClient.m, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsN3ixnKsTU7pVCYZc:-KUsj1fMXYIPxvJT9Z0y:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/model/SickVacationClient.m#L26)):*
<details><summary><i>Previously, ecbrady wrote…</i></summary>
> How would I do that with the JSON data saved into a dictionary and not an array?
</details>
Done.

---

*[byuSuite/Apps/SickVacation/model/ByuSickVacationLeavePlan.m, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsNP1h7cjUH6J4P2zh:-KUsj4wF1f9vy7f4mLzE:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/model/ByuSickVacationLeavePlan.m#L18)):*
<details><summary><i>Previously, ecbrady wrote…</i></summary>
> This seems to work but is it right?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9)*

**Comment by romrell4** [comment]
Reviewed 17 of 18 files at r3.
Review status: 9 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsksJA5jfxAavWEJVt:-KUsksJBOyAePL3rpbxA:btqt8ti) (no related file):*
Change manifest so that MapMyClasses has a description that says: "This feature will allow students to view their schedule for finals and map out where each final will be held."

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsM3GG47UIf2JYfYzf:-KUsk6vRNA-YAIg3t6jW:b-skhf98) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L39)):*
<details><summary><i>Previously, ecbrady wrote…</i></summary>
> Currently we need to. I think there's something in the Storyboard though that I could change so we dont need to.
</details>
Let's look into that

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 41 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsM8alvnHCNZeZ1AJi:-KUsk3nVD5YMdWnNbGYn:b-m2tghc) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L41)):*
<details><summary><i>Previously, ecbrady wrote…</i></summary>
> Done.
</details>
Look into the dev code to see if this is correct

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsksJA5jfxAavWEJVt:-KUsmO1IsPLb7bXYoVgK:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Change manifest so that MapMyClasses has a description that says: "This feature will allow students to view their schedule for finals and map out where each final will be held."
</details>
Done.

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsM3GG47UIf2JYfYzf:-KUsnMN5T2iYUtSfkQAP:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L39)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Let's look into that
</details>
Done.

---

*[byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m, line 41 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-KUsM8alvnHCNZeZ1AJi:-KUsm4v9CGJv4nGMaVaE:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/bcb4f0e662f19d262d6ed74c95b168ef15d8256f/byuSuite/Apps/SickVacation/controller/SickVacationMainViewController.m#L41)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Look into the dev code to see if this is correct
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9)*

**Comment by romrell4** [comment]
Reviewed 2 of 3 files at r5.
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9)*

**Comment by romrell4** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/9#-:-KUsr0WIoiR9U4Jk4aWP:bnfp4nl)*

**Pull request merged**
