### PR TITLE
Hotfix/byu map view controller

### PR DESCRIPTION
**Pull request by nateyj**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/112)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 6 of 8 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/112)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/112#-KdXDmpaofBygmrJcPf-:-KdXDmpbZ9UIceV24mp6:b-lycwnw) (no related file):*
Fix OCH

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/112)*

**Comment by nateyj** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/112#-KdXDmpaofBygmrJcPf-:-KdXG5y26BABN1445t3L:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Fix OCH
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/112)*

**Comment by romrell4** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/112#-:-KdXGModhJUHgH4W08HL:bnfp4nl)*

**Pull request merged**
