### PR TITLE
Hotfix/calendars

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/165)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 19 of 27 files at r1, 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m, line 25 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifZakIdT8m6_TwCBtM:-KifZakIdT8m6_TwCBtN:bi6t693) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ca1a823f454e081c743e331a0d6ad6bcc6e2990b/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m#L25)):*
> ```objc
>     [super viewDidLoad];
>     
>     self.tableView.estimatedRowHeight = 44.0;                   //Arbitrary value, set to default cell height
> ```

Talk to me about a swift extension for this

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m, line 56 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifZvz_3hT62n-dTP5U:-KifZvz_3hT62n-dTP5V:b-f8kyv1) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ca1a823f454e081c743e331a0d6ad6bcc6e2990b/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m#L56)):*
> ```objc
>     UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:cellData[@"cell"]];
>     cell.textLabel.text = cellData[@"text"];
>     cell.textLabel.numberOfLines = 0;
> ```

So every cell's main text can wrap? Is this the intention?

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m, line 61 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-Kif_5UdPoNiles1P4Pz:-Kif_5UdPoNiles1P4Q-:b-7zeecz) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ca1a823f454e081c743e331a0d6ad6bcc6e2990b/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m#L61)):*
> ```objc
>     if (cellData[@"action"]) {
>         cell.userInteractionEnabled = YES;
>     }
> ```

You might need an else here (or else it might recycle values)

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m, line 17 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-Kifb5TTHke_rJyQUXdb:-Kifb5TTHke_rJyQUXdc:b-arhnjo) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ca1a823f454e081c743e331a0d6ad6bcc6e2990b/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m#L17)):*
> ```objc
> 
> @property (weak, nonatomic) IBOutlet UITableView *tableView;
> @property (weak, nonatomic) IBOutlet UIView *tableFooter;
> ```

What does the tableFooter text start out with?

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m, line 32 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifaQdADlxXMx_2oBg9:-KifaQdADlxXMx_2oBgA:b-btpm48) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ca1a823f454e081c743e331a0d6ad6bcc6e2990b/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m#L32)):*
> ```objc
>     
>     self.events = [NSMutableArray array];
>     [self loadThreeMonthsEventsWithStartDate:[NSDate date]];
> ```

Let's rename this function to make it not as specific to the months. In fact, let's pass in the number of months to load.

`[self loadEventsFromDate:startDate forMonths:MONTHS]`

That makes it much easier to change in the future

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m, line 88 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifbSOemtfGBBHiPT7U:-KifbSOemtfGBBHiPT7V:bseng3b) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ca1a823f454e081c743e331a0d6ad6bcc6e2990b/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m#L88)):*
> ```objc
>         } else {
>             if (events.count > 0) {
>                 [self.events addObjectsFromArray:events];
> ```

Will this keep the ordering correct? Do we need to order before adding?

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.m, line 69 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifbjGZ1h4W--aUs2ow:-KifbjGZ1h4W--aUs2ox:bbfjm2q) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ca1a823f454e081c743e331a0d6ad6bcc6e2990b/byuSuite/Apps/Calendars/controller/CalendarsViewController.m#L69)):*
> ```objc
>             [self showError:error];
>         } else {
>             self.calendarCategories = categories;
> ```

Weren't we going to add Academic Calendar manually here?

---

*[byuSuite/Apps/Calendars/model/CalendarEvent.m, line 21 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifcEzvpHA9TqQxxBZ0:-KifcEzvpHA9TqQxxBZ1:b41vdnk) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ca1a823f454e081c743e331a0d6ad6bcc6e2990b/byuSuite/Apps/Calendars/model/CalendarEvent.m#L21)):*
> ```objc
>     me.eventId = [me checkClassOfObject:[dictionary nullSafeObjectForKey:@"EventId"]];
>     me.title = [me checkClassOfObject:[[dictionary nullSafeObjectForKey:@"Title"] stringByDecodingHTMLEntities]];
>     me.eventDescription = [[me checkClassOfObject:[[dictionary nullSafeObjectForKey:@"Description"] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]]] stringByDecodingHTMLEntities];
> ```

I think you'll want the other order, right? What if there were a bunch of <br />s in the string? You'd want decode them, then trim the whitespace and newlines, right?

---

*[byuSuite/Apps/Calendars/model/CalendarEvent.m, line 62 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifcXT0ZyYFo1dN-daa:-KifcXT0ZyYFo1dN-dab:b-pm5lmr) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ca1a823f454e081c743e331a0d6ad6bcc6e2990b/byuSuite/Apps/Calendars/model/CalendarEvent.m#L62)):*
> ```objc
> 
> -(NSString *)checkClassOfObject:(id)object {
>     return [object isKindOfClass:[NSString class]] ? object : nil;
> ```

Comment here about why you do this

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.m, line 32 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-Kifd7JFx3NhtovZ1s9P:-Kifd7JG5q5SweNeFctz:b58r42n) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ca1a823f454e081c743e331a0d6ad6bcc6e2990b/byuSuite/Apps/Calendars/model/CalendarsClient.m#L32)):*
> ```objc
>             
>             //Get Categories from response
>             NSMutableArray<CalendarCategory *> *categories = [[dataArray transformWithBlock:^id(NSDictionary *dictionary) {
> ```

This won't need to be mutable anymore

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.m, line 36 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifcrB8jU24yMOjsbsL:-KifcrB8jU24yMOjsbsM:b-9b2oz0) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ca1a823f454e081c743e331a0d6ad6bcc6e2990b/byuSuite/Apps/Calendars/model/CalendarsClient.m#L36)):*
> ```objc
>             }] mutableCopy];
>             //Add Academic Calendar to categories
>             [categories addObject:[CalendarCategory calendarCategoryWithDictionary:@{@"CategoryId": ACADEMIC_CAL_ID, @"Name": ACADEMIC_CAL_NAME/*, @"FullUrl": ACADEMIC_CAL_URL*/}]];
> ```

Ah! I see! Let's add this in the VC just to avoid confusion. The model shouldn't reflect business logic. Just load data from URLs

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.m, line 49 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifdIKn3CDREHw4aj3s:-KifdIKn3CDREHw4aj3t:b-191x1p) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ca1a823f454e081c743e331a0d6ad6bcc6e2990b/byuSuite/Apps/Calendars/model/CalendarsClient.m#L49)):*
> ```objc
> 
> +(void)getCalendarEventsWithCategoryId:(NSString *)categoryId startDate:(NSString *)startDate endDate:(NSString *)endDate andCallBack:(void (^)(NSArray<CalendarEvent *> *, ByuError *))callback {
>     ByuRequest *request = [ByuRequest requestWithMethod:GET andUrl:[self urlWithBaseUrl:BASE_URL pathParams:@[@"Events"] andQueryParams:@{@"categories": categoryId, @"event[min][date]": startDate, @"event[max][date]": endDate}]];
> ```

What are these queryParams? They seem... odd... to me... I think they might accidentally get URL encoded

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165)*

**Comment by ecbrady** [comment]
Review status: 23 of 26 files reviewed at latest revision, 12 unresolved discussions.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m, line 56 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifZvz_3hT62n-dTP5U:-Kig9fb9gGE_2Ym_goMd:b-epc94m) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m#L56)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

So every cell's main text can wrap? Is this the intention?
</blockquote></details>

I believe so.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m, line 61 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-Kif_5UdPoNiles1P4Pz:-KigA0ngduibyK1PfdHY:b-lbut5x) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m#L61)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You might need an else here (or else it might recycle values)
</blockquote></details>

What do you mean?

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m, line 17 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-Kifb5TTHke_rJyQUXdb:-KigA7faKlqc6apU-mDj:b-9sa8lz) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What does the tableFooter text start out with?
</blockquote></details>

It's initialized to Getting Results...

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m, line 32 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifaQdADlxXMx_2oBg9:-KigB_OIaSRTIOdihvmK:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's rename this function to make it not as specific to the months. In fact, let's pass in the number of months to load.

`[self loadEventsFromDate:startDate forMonths:MONTHS]`

That makes it much easier to change in the future
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m, line 88 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifbSOemtfGBBHiPT7U:-KigBiwZdyjPa67KCkzF:bvzwmlt) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m#L88)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Will this keep the ordering correct? Do we need to order before adding?
</blockquote></details>

Yeah because we're sorting by date they'll stay in order when added to the array. It makes more sense to me to sort before adding so we're only sorting a small packet instead of sorting the entire list multiple times.

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.m, line 69 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifbjGZ1h4W--aUs2ow:-KigCAfn7QgBarm9aMja:bajb8ka) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/controller/CalendarsViewController.m#L69)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Weren't we going to add Academic Calendar manually here?
</blockquote></details>

No. We do it in the client so that the view controller gets one list of all of them.

---

*[byuSuite/Apps/Calendars/model/CalendarEvent.m, line 21 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifcEzvpHA9TqQxxBZ0:-KigETGN7T_l46o25OLF:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/model/CalendarEvent.m#L21)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think you'll want the other order, right? What if there were a bunch of <br />s in the string? You'd want decode them, then trim the whitespace and newlines, right?
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/model/CalendarEvent.m, line 62 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifcXT0ZyYFo1dN-daa:-KigEqA8oUjbjj78nUGR:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/model/CalendarEvent.m#L62)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment here about why you do this
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.m, line 36 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifcrB8jU24yMOjsbsL:-KigFklEYw9jYSG5UHTL:bd3p485) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/model/CalendarsClient.m#L36)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Ah! I see! Let's add this in the VC just to avoid confusion. The model shouldn't reflect business logic. Just load data from URLs
</blockquote></details>

We'd be generating the CalendarCategory object from the VC. Would that be okay?

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.m, line 49 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifdIKn3CDREHw4aj3s:-KigFvObFZkOSJss04CM:b-9k6ezo) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/model/CalendarsClient.m#L49)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What are these queryParams? They seem... odd... to me... I think they might accidentally get URL encoded
</blockquote></details>

They seem odd to me as well. Those are the query params Katria gave me. So far they seem to be working without being url encoded

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165)*

**Comment by romrell4** [comment]
Reviewed 1 of 8 files at r4, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m, line 61 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-Kif_5UdPoNiles1P4Pz:-KigS2MDOIXk5n1-fgGM:bkjhfbk) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m#L61)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

When you use "dequeueReusableCell...", it gives you a recycled cell... Sometime, it already has stuff from being previously loaded. You'll overwrite most of that, but if you don't have an else here, it might have started with userInteractionEnabled as YES, and you won't reset it. Talk to me if you have questions

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m, line 88 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifbSOemtfGBBHiPT7U:-KigS_tnW7rpnliwdbvC:b-u1fnkc) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m#L88)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Yeah because we're sorting by date they'll stay in order when added to the array. It makes more sense to me to sort before adding so we're only sorting a small packet instead of sorting the entire list multiple times.
</blockquote></details>

Where do we do the sorting? If that's in the client, it should be here. 

That makes sense. Let's put a comment explaining why that works (the sorting of small batches)

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.m, line 69 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifbjGZ1h4W--aUs2ow:-KigSt55fGzJvqpUwmZ-:bfik6t9) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/controller/CalendarsViewController.m#L69)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

No. We do it in the client so that the view controller gets one list of all of them.
</blockquote></details>

Move that into here. That's business logic that the client shouldn't have to worry about. It should only be worried about making async calls and parsing data

---

*[byuSuite/Apps/Calendars/model/CalendarEvent.m, line 21 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifcEzvpHA9TqQxxBZ0:-KigTISc4pT05Mt6VdtJ:b-9oxxji) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/model/CalendarEvent.m#L21)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Reorder the other ones as well

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.m, line 36 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifcrB8jU24yMOjsbsL:-KigTVeiqB3KNYcWkVSk:b2nhtan) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/model/CalendarsClient.m#L36)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

We'd be generating the CalendarCategory object from the VC. Would that be okay?
</blockquote></details>

Yup

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.m, line 49 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifdIKn3CDREHw4aj3s:-KigT_YGCHRaRmjcakrg:b-u402xb) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/model/CalendarsClient.m#L49)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

They seem odd to me as well. Those are the query params Katria gave me. So far they seem to be working without being url encoded
</blockquote></details>

I think they'll break with swift.... Could you check if "[" and "]" will get urlencoded?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m, line 61 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-Kif_5UdPoNiles1P4Pz:-Kj4Hgg8pHY2vbjH8E4r:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m#L61)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

When you use "dequeueReusableCell...", it gives you a recycled cell... Sometime, it already has stuff from being previously loaded. You'll overwrite most of that, but if you don't have an else here, it might have started with userInteractionEnabled as YES, and you won't reset it. Talk to me if you have questions
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m, line 88 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifbSOemtfGBBHiPT7U:-Kj4JJFj7vTTPmBgcsQC:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/controller/CalendarsEventsViewController.m#L88)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Where do we do the sorting? If that's in the client, it should be here. 

That makes sense. Let's put a comment explaining why that works (the sorting of small batches)
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/controller/CalendarsViewController.m, line 69 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifbjGZ1h4W--aUs2ow:-Kj4JtNmtOcwgPMonGKt:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/controller/CalendarsViewController.m#L69)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Move that into here. That's business logic that the client shouldn't have to worry about. It should only be worried about making async calls and parsing data
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/model/CalendarEvent.m, line 21 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifcEzvpHA9TqQxxBZ0:-Kj4I019ZcaonGxDm0W8:brdb41i) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/model/CalendarEvent.m#L21)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Reorder the other ones as well
</blockquote></details>

There's nothing to reorder on the others. They only trim. This is the only one that did both decoding and trimming.

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.m, line 32 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-Kifd7JFx3NhtovZ1s9P:-Kj4JuJsN2KGMtHjbp3e:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/model/CalendarsClient.m#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This won't need to be mutable anymore
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.m, line 36 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifcrB8jU24yMOjsbsL:-Kj4JvN1Go-tfDC9pd8W:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/model/CalendarsClient.m#L36)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Yup
</blockquote></details>

Done.

---

*[byuSuite/Apps/Calendars/model/CalendarsClient.m, line 49 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-KifdIKn3CDREHw4aj3s:-Kj4IL3JA0qaIu8Q547Y:b-lu73ml) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d8f381d4db4d0cc82505c165b9b0fde52d40d51a/byuSuite/Apps/Calendars/model/CalendarsClient.m#L49)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think they'll break with swift.... Could you check if "[" and "]" will get urlencoded?
</blockquote></details>

It looks like they are urlencoded but it still seems to work...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m, line 60 at r7](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-Kj4d6CqkMy2dzct5U7z:-Kj4d6CsAFA4zIozsKxb:b-ebzo85) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ebc3325828efa21b7b2b5dacd60f279e3a7fddb2/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m#L60)):*
> ```objc
>     
>     if (cellData[@"action"]) {
>         cell.userInteractionEnabled = YES;
> ```

You might be able to do this with ternary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m, line 60 at r7](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-Kj4d6CqkMy2dzct5U7z:-Kj4e8hsAf8HzAnFdFN6:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ebc3325828efa21b7b2b5dacd60f279e3a7fddb2/byuSuite/Apps/Calendars/controller/CalendarsEventDetailViewController.m#L60)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You might be able to do this with ternary
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165#-Kj8wHr7ik7wcANu1Cw6:-Kj8wHr7ik7wcANu1Cw7:b-xch9ss) (no related file):*
Switch to PROD url

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/165)*

**Pull request merged**
