### PR TITLE
Hotfix/id card

### PR DESCRIPTION
**Pull request by nateyj**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/103)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 33 of 33 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.m, line 52 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103#-KcerS3gwPD73Yla0elT:-KcerS3gwPD73Yla0elU:b-vhzybi) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/f60913a639e428cc8ae7b42551a342c2c124e07b/byuSuite/Apps/IDCard/controller/IDCardViewController.m#L52)):*
> ```objc
>     self.byuIDLabel.text = @"";
>     self.issueNumberLabel.text = @"";
>     self.expirationDateLabel.text = @"EXP";
> ```

It seems that we don't have to set this here... Also, won't all of these text's already be set to @""?

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.m, line 103 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103#-Kces1mjCccbpv5iDI8k:-Kces1mkY6Sfvp7P93uJ:b-tqrdzi) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/f60913a639e428cc8ae7b42551a342c2c124e07b/byuSuite/Apps/IDCard/controller/IDCardViewController.m#L103)):*
> ```objc
>             [self showError:error];
>         } else {
>             [self loadPersonImage];
> ```

Why don't we made these calls at the same time? We shouldn't have to wait for the ID info to get back before loading the image

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.m, line 121 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103#-KcesNPIVhEgaRodD8Cr:-KcesNPIVhEgaRodD8Cs:bg0btf3) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/f60913a639e428cc8ae7b42551a342c2c124e07b/byuSuite/Apps/IDCard/controller/IDCardViewController.m#L121)):*
> ```objc
>             self.issueNumberLabel.text = idCard.issueNumber;
>             
>             NSDateFormatter *dateFormatter1 = [[NSDateFormatter alloc] init];
> ```

Let's just do this first format in the model (when we deserialize it). That way the expirationDate will actually be saved as an NSDate, and here we will only use the second format

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103)*

**Comment by nateyj** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.m, line 52 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103#-KcerS3gwPD73Yla0elT:-KcsKhhzpUnGj_Sno10C:barthw4) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/f60913a639e428cc8ae7b42551a342c2c124e07b/byuSuite/Apps/IDCard/controller/IDCardViewController.m#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

It seems that we don't have to set this here... Also, won't all of these text's already be set to @""?
</blockquote></details>

I'm not exactly sure, but when I was testing, if the request took longer than usual, the placeholder text I had in the storyboard shows up on the device. So to avoid that I just cleared everything initially

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.m, line 103 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103#-Kces1mjCccbpv5iDI8k:-KcsMIQa_p2yvBLu_iKv:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/f60913a639e428cc8ae7b42551a342c2c124e07b/byuSuite/Apps/IDCard/controller/IDCardViewController.m#L103)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why don't we made these calls at the same time? We shouldn't have to wait for the ID info to get back before loading the image
</blockquote></details>

Done.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.m, line 121 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103#-KcesNPIVhEgaRodD8Cr:-KcsOxwzDq5aI_C14I5h:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/f60913a639e428cc8ae7b42551a342c2c124e07b/byuSuite/Apps/IDCard/controller/IDCardViewController.m#L121)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's just do this first format in the model (when we deserialize it). That way the expirationDate will actually be saved as an NSDate, and here we will only use the second format
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.m, line 132 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103#-Kcs_2b_7YcYRxUASPdo:-Kcs_2bcSvc4pjekePdg:b-dv91vt) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/34800d77d9c210f42a6ac2fc1899b2e4e573840b/byuSuite/Apps/IDCard/controller/IDCardViewController.m#L132)):*
> ```objc
>     }];
>     
>     [self loadPersonImage];
> ```

You can probably inline this function if we never reload the data

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103)*

**Comment by nateyj** [comment]
Review status: 28 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/IDCard/controller/IDCardViewController.m, line 132 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103#-Kcs_2b_7YcYRxUASPdo:-KcsaDx30ZOGer8tcvMu:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/34800d77d9c210f42a6ac2fc1899b2e4e573840b/byuSuite/Apps/IDCard/controller/IDCardViewController.m#L132)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You can probably inline this function if we never reload the data
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/103)*

**Pull request merged**
