### PR TITLE
Hotfix/regyear terms

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/18)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 22 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBooI3USi_nflWAxuT:-KVBooI3USi_nflWAxuU:bi8q9lz) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L22)):*
> ```objc
> @property (nonatomic) ByuBooklist *byuBooklist;
> @property (nonatomic) ByuCurrentYearTerm *byuCurrentYearTerm;
> @property (nonatomic) BOOL currentYearTermLoaded;
> ```

This should also be able to go away to be replaced with whether or not byuCurrentYearTerm is nil

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 24 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBoM85SYzXUnMFnrqd:-KVBoM85SYzXUnMFnrqe:b-ei6o61) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L24)):*
> ```objc
> @property (nonatomic) BOOL currentYearTermLoaded;
> @property (nonatomic) NSArray<NSString *> *yearTerms;
> @property (nonatomic) BOOL yearTermsLoaded;
> ```

We should be able to replace this with whether or not yearTerms is nil, right?

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 84 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBphgfgkc5BYqsZJ59:-KVBphggKQaVLjIKC5NB:biz6axb) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L84)):*
> ```objc
> }
> 
> -(void)loadData {
> ```

Rename this function to loadBooklist

---

*[byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m, line 22 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBq1Szp2v6ImUMrOnO:-KVBq1Szp2v6ImUMrOnP:bl2eh8e) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m#L22)):*
> ```objc
> @property (nonatomic) NSArray *departmentsToDisplay;
> @property (nonatomic) ByuRegistrationYearTerm *yearTerm;   //The year term selected by the user on the previous screen.
> @property (nonatomic) BOOL yearTermLoaded;
> ```

May be able to remove this

---

*[byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m, line 24 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBpvHT0P_02qJvko7m:-KVBpvHT0P_02qJvko7n:bl2eh8e) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m#L24)):*
> ```objc
> @property (nonatomic) BOOL yearTermLoaded;
> @property (nonatomic) NSArray<NSString *> *yearTerms;
> @property (nonatomic) BOOL yearTermsLoaded;
> ```

May be able to remove this

---

*[byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m, line 222 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBqD7vexkSyyYw8ySl:-KVBqD7w7Z9EKPTbablv:bqvcbk1) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m#L222)):*
> ```objc
> 
> -(void)createButtonFailed:(SemesterButton *)button {
>     
> ```

What are these? I guess they didn't do anything before either...?

---

*[byuSuite/Classes/ReusableClients/RegYearTermsClient.h, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBqZuYCSWqzO26Kz3i:-KVBqZuYCSWqzO26Kz3j:b-ddd6pe) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Classes/ReusableClients/RegYearTermsClient.h#L14)):*
> ```objc
> @interface RegYearTermsClient : ByuClient
> 
> +(void)getRegistrationYearTermsWithCallBack:(void (^) (NSArray<NSString *> *yearTerms, ByuError *error))callback;
> ```

Let's return an nsarray of RegYearTerm objects. Talk to me about it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18)*

**Comment by ecbrady** [comment]
Review status: 2 of 13 files reviewed at latest revision, 7 unresolved discussions.

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 22 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBooI3USi_nflWAxuT:-KVVn36q_3sRe5ngSa3X:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L22)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> This should also be able to go away to be replaced with whether or not byuCurrentYearTerm is nil
</details>
Done.

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 24 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBoM85SYzXUnMFnrqd:-KVVn3YUK_6aGE5M7Omf:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L24)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> We should be able to replace this with whether or not yearTerms is nil, right?
</details>
Done.

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 84 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBphgfgkc5BYqsZJ59:-KVVnJnlq83S6dI4mGUh:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L84)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Rename this function to loadBooklist
</details>
Done.

---

*[byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m, line 22 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBq1Szp2v6ImUMrOnO:-KVVqYwwcPnujptQ3WMK:b-d2c9ej) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m#L22)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> May be able to remove this
</details>
This one cannot be removed...

---

*[byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m, line 24 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBpvHT0P_02qJvko7m:-KVVqX8MKd5N_cYcNLL-:btvtry9) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m#L24)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> May be able to remove this
</details>
Done. This one yes. It is unused.

---

*[byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m, line 222 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBqD7vexkSyyYw8ySl:-KVVqgJFaI40z7XteDCq:b-ioh23y) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m#L222)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> What are these? I guess they didn't do anything before either...?
</details>
No they didn't do anything but they are required for the delegate to work... I think. All I know is it crashed when I tried taking them out.

---

*[byuSuite/Classes/ReusableClients/RegYearTermsClient.h, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVBqZuYCSWqzO26Kz3i:-KVW5in-VSL0ST4qpI0d:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/7538ae6f580b1ed1e4d3586510c6b3ea8b360411/byuSuite/Classes/ReusableClients/RegYearTermsClient.h#L14)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Let's return an nsarray of RegYearTerm objects. Talk to me about it
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18)*

**Comment by romrell4** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Classes/ReusableUI/SemesterButton/SemesterButton.m, line 32 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVWFkSwePQNV89cNdhO:-KVWFkSwePQNV89cNdhP:bor3j66) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/795ffcc1e8170edd5dcc69a793e1df9859f73bcc/byuSuite/Classes/ReusableUI/SemesterButton/SemesterButton.m#L32)):*
> ```objc
>         } else {
>             semButton.yearTerms = yearTerms;
>             [semButton setTitle:[semButton.yearTerms objectAtIndex:0].title];
> ```

Use [] instead. Also, put a comment above this saying that we are using the first item in the list as the default year term

---

*[byuSuite/Classes/ReusableUI/SemesterButton/SemesterButton.m, line 60 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVWG0GKMCeQojgYxOJJ:-KVWG0GKMCeQojgYxOJK:b-pb44rm) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/795ffcc1e8170edd5dcc69a793e1df9859f73bcc/byuSuite/Classes/ReusableUI/SemesterButton/SemesterButton.m#L60)):*
> ```objc
>     NSMutableArray *buttonTitles = [NSMutableArray array];
>     for (RegYearTerm *yearTerm in self.yearTerms) {
>         NSString *buttonTitle = yearTerm.title;
> ```

inline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Classes/ReusableUI/SemesterButton/SemesterButton.m, line 32 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVWFkSwePQNV89cNdhO:-KV_r-JjoyP8R6WNg-XI:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/795ffcc1e8170edd5dcc69a793e1df9859f73bcc/byuSuite/Classes/ReusableUI/SemesterButton/SemesterButton.m#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Use [] instead. Also, put a comment above this saying that we are using the first item in the list as the default year term
</details>
Done.

---

*[byuSuite/Classes/ReusableUI/SemesterButton/SemesterButton.m, line 60 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18#-KVWG0GKMCeQojgYxOJJ:-KV_r8rYD4kpWQQXeqoa:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/795ffcc1e8170edd5dcc69a793e1df9859f73bcc/byuSuite/Classes/ReusableUI/SemesterButton/SemesterButton.m#L60)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> inline
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/18)*

**Pull request merged**
