### PR TITLE
Hotfix/ls

### PR DESCRIPTION
**Pull request by nateyj**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/77)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/LearningSuite/view/LearningSuite.storyboard, line 672 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/77#-KbkKxaDQiRLepz8O5Nf:-KbkKxaDQiRLepz8O5Ng:b3x266z) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8f74aff1f8a870b3874bb92bebe2dcebdc4f634e/byuSuite/Apps/LearningSuite/view/LearningSuite.storyboard#L672)):*
> ```XML
>                                 <nil key="highlightedColor"/>
>                             </label>
>                             <tableView clipsSubviews="YES" contentMode="scaleToFill" alwaysBounceVertical="YES" dataMode="prototypes" style="plain" separatorStyle="default" allowsSelection="NO" rowHeight="44" sectionHeaderHeight="28" sectionFooterHeight="28" translatesAutoresizingMaskIntoConstraints="NO" id="Jab-Zw-Vt3">
> ```

Revert this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/77)*

**Comment by nateyj** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/LearningSuite/view/LearningSuite.storyboard, line 672 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/77#-KbkKxaDQiRLepz8O5Nf:-KbkLNcN25FBlTwVcufq:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8f74aff1f8a870b3874bb92bebe2dcebdc4f634e/byuSuite/Apps/LearningSuite/view/LearningSuite.storyboard#L672)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Revert this one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/77)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/77)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/77#-:-KbkLVn0luaLb0CYFR7H:bnfp4nl)*

**Pull request merged**
