### PR TITLE
Swift/auth2

### PR DESCRIPTION
**Pull request by romrell4**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/156)

### CODE REVIEW

**Comment by ecbrady** [comment]
Reviewed 24 of 25 files at r1.
Review status: 20 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/NewCredentialHandler/Authentication/OauthToken2.swift, line 36 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/156#-KiBxqns_li_aPxAuJKn:-KiBxqns_li_aPxAuJKo:b-z12456) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/074c4233366fd5d2c02d90845661374e888110f2/byuSuite/Classes/NewCredentialHandler/Authentication/OauthToken2.swift#L36)):*
> ```Swift
>     
>     func isExpired() -> Bool {
>         //If the value on the left (now) is not less than the value on the left (expirationDate)
> ```

Value on left less than value on left...?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/156)*

**Comment by romrell4** [comment]
Review status: 20 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/NewCredentialHandler/Authentication/OauthToken2.swift, line 36 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/156#-KiBxqns_li_aPxAuJKn:-KiBzpBXmSVqRVrSg6en:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/074c4233366fd5d2c02d90845661374e888110f2/byuSuite/Classes/NewCredentialHandler/Authentication/OauthToken2.swift#L36)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Value on left less than value on left...?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/156)*

**Comment by ecbrady** [comment]
:lgtm:

---

Reviewed 1 of 25 files at r1.
Review status: 20 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/156#-:-KiC5hxtkkCTvBR-Ra76:bnfp4nl)*

**Comment by ecbrady** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/156)*

**Pull request merged**
