### PR TITLE
Hotfix/copyright

### PR DESCRIPTION
**Pull request by romrell4**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/139)

### CODE REVIEW

**Comment by nateyj** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-KgtvIG1iLbv2zhuLb4J:-KgtvIG1iLbv2zhuLb4K:b3pibjk) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L19)):*
> ```Swift
>     static let BYU_COMPLIANCE_HOTLINE = URL(string: "tel:888-238-1062")!
>     
>     var contactOptions = Dictionary<String, ((UIAlertAction?) -> Void)>()
> ```

Is it possible to use [<key>: <value>] syntax instead of Dictionary<key, value> when using a closure like that?

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 32 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-KgtxrUDYeCK7Qe74EER:-KgtxrUDYeCK7Qe74EES:b-vu3iy6) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L32)):*
> ```Swift
>         super.viewDidLoad()
>         
>         self.tableView.applyBYUFormattingHidingEmptyCells()
> ```

From what I've seen in Swift, it's common to not specify `self` because it's inferred unless the situation needs it to be explicitly expressed. Obviously, it works either way. Should we leave them in to keep it consistent with the Objective-C stuff or just move forward with Swift common practices?

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-KgtySQAFqk99tn_VZ1O:-KgtySQAFqk99tn_VZ1P:bmvjcqp) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L57)):*
> ```Swift
>     
>     func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
>         let cell = tableView.dequeueReusableCell(withIdentifier: "cell")!
> ```

Instead of force unwrapping, you could use `dequeueReusableCell(withIdentifier:forIndexPath:)` since it guarantees a `UITableViewCell` is returned assuming the identifier is registered. This removes the need to worry about an optional `UITableViewCell`

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 69 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-Kgu09nkcNv_Wt_V4UO0:-Kgu09nkcNv_Wt_V4UO1:b-hmd3ps) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L69)):*
> ```Swift
>             //Contact us
>             showContactOptionsActionSheet(cell: tableView.cellForRow(at: indexPath))
>             break
> ```

Swift `switch` statements actually don't require `break` in each `case` if you do not want to include them.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-Kgu0lYOFXm2o7ppaPiB:-Kgu0lYOFXm2o7ppaPiC:b-3kqo93) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L101)):*
> ```Swift
>     func loadContactOptions() {
>         self.contactOptions = [
>             "Call": {(action:UIAlertAction?) in
> ```

I've been meaning to submit a fix for this for a while now, but what do you think about including the phone number in the contact option title itself? E.g., "Call (801) xxx-xxx" or even just the number itself. I notice with a lot of apps that direct a user to call a number, they'll just display the number itself in the option

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 143 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-KgtxRGCCDORV_7X_lUN:-KgtxRGCCDORV_7X_lUO:b-eod0sq) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L143)):*
> ```Swift
>     
>     static func open(url: URL) {
>         if #available(iOS 10.0, *) {
> ```

Thank goodness we have this now!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 69 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-Kgu09nkcNv_Wt_V4UO0:-Kgu21SWn8zba80sjfLc:bs16ow3) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L69)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary><blockquote>

Swift `switch` statements actually don't require `break` in each `case` if you do not want to include them.
</blockquote></details>

Wait, so it won't fall through?

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-Kgu0lYOFXm2o7ppaPiB:-Kgu39inn0m-N3Ysvmy3:b20i1cl) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L101)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary><blockquote>

I've been meaning to submit a fix for this for a while now, but what do you think about including the phone number in the contact option title itself? E.g., "Call (801) xxx-xxx" or even just the number itself. I notice with a lot of apps that direct a user to call a number, they'll just display the number itself in the option
</blockquote></details>

You just mean adding the phone number to the action sheet? I'm down with that :)

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 143 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-KgtxRGCCDORV_7X_lUN:-Kgu3H54lfxjfPW_zXdO:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L143)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary><blockquote>

Thank goodness we have this now!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-KgtvIG1iLbv2zhuLb4J:-Kgu3UanfXPkYiy_1_KG:b-f5ssyt) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L19)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary><blockquote>

Is it possible to use [<key>: <value>] syntax instead of Dictionary<key, value> when using a closure like that?
</blockquote></details>

How would it look? I've never tried it...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139)*

**Comment by romrell4** [comment]
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 32 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-KgtxrUDYeCK7Qe74EER:-Kgu46tc8ccQJd2j0znQ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L32)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary><blockquote>

From what I've seen in Swift, it's common to not specify `self` because it's inferred unless the situation needs it to be explicitly expressed. Obviously, it works either way. Should we leave them in to keep it consistent with the Objective-C stuff or just move forward with Swift common practices?
</blockquote></details>

Done.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-KgtySQAFqk99tn_VZ1O:-Kgu4WWsMrBIfeW-pzd4:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L57)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary><blockquote>

Instead of force unwrapping, you could use `dequeueReusableCell(withIdentifier:forIndexPath:)` since it guarantees a `UITableViewCell` is returned assuming the identifier is registered. This removes the need to worry about an optional `UITableViewCell`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139)*

**Comment by nateyj** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-KgtvIG1iLbv2zhuLb4J:-KgyoUJGWwE7QsUFCiMR:b-71sm3o) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L19)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

How would it look? I've never tried it...
</blockquote></details>

`[String: (UIAlertAction?) -> Void]()`

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 69 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-Kgu09nkcNv_Wt_V4UO0:-Kgyok4GmmGsA_YcON7O:bh0lmrz) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L69)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Wait, so it won't fall through?
</blockquote></details>

That's correct! I would test it just to make sure though

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-Kgu0lYOFXm2o7ppaPiB:-KgyoxiCEjknD9UtYre6:blxd45a) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L101)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You just mean adding the phone number to the action sheet? I'm down with that :)
</blockquote></details>

Sweet. I say let's do it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139)*

**Comment by romrell4** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-KgtvIG1iLbv2zhuLb4J:-Kgz9tWXu6I-MVYreDYk:btb66kr) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L19)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary><blockquote>

`[String: (UIAlertAction?) -> Void]()`
</blockquote></details>

Totally worked :)

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 69 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-Kgu09nkcNv_Wt_V4UO0:-KgzAba81ILPGaSpWEJd:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L69)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary><blockquote>

That's correct! I would test it just to make sure though
</blockquote></details>

Done.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-Kgu0lYOFXm2o7ppaPiB:-KgzAin_6Y2hr9U1nnqm:b-bho0ik) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L101)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary><blockquote>

Sweet. I say let's do it
</blockquote></details>

Oh... but the way we save our phone numbers might make that difficult... Let's not do this for this phase, but let's put it on the list of issues so that we do all the features at once. Could you make the issue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139)*

**Comment by romrell4** [comment]
Reviewed 6 of 9 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139)*

**Comment by nateyj** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-Kgu0lYOFXm2o7ppaPiB:-Kgzgu_sfjQZfRX8uZLq:bebrt1w) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/40df553af57998f6767856f9f25d3b56c6c5f6b0/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L101)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Oh... but the way we save our phone numbers might make that difficult... Let's not do this for this phase, but let's put it on the list of issues so that we do all the features at once. Could you make the issue?
</blockquote></details>

Will do

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/139#-:-KgzhvhpKtm1gGXAVxbx:bnfp4nl)*

**Pull request merged**
