### PR TITLE
hotfix/restrooms2

### PR DESCRIPTION
**Pull request by nateyj**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/29)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/DepartmentDirectory/controller/DepartmentDirectoryListingViewController.m, line 215 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEmk3BYOj_dhz18orq:-KWEmk3BYOj_dhz18orr:bthhu60) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/DepartmentDirectory/controller/DepartmentDirectoryListingViewController.m#L215)):*
> ```objc
>             CampusBuildingsMapViewController *vc = [[CampusBuildingsMapViewController alloc] initWithNibName:BUILDINGS_MAP_VIEW_NIB_NAME bundle:nil];
>             
>             //TODO: self.listing.building is the building acronym and doesn't need to be parsed from self.listing.location
> ```

Remove TODO and solve it

---

*[byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m, line 297 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEmZwwCFOz_hI1a5A6:-KWEmZwxJ9kY6HjlyuID:b-45swy4) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m#L297)):*
> ```objc
>             [self.map zoomToFitMapAnnotationsWithUserLocation:YES];
>         } else {
>             [self setMapZoomForiPad:self.map];
> ```

Is there a difference on iPad

---

*[byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m, line 337 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEmsoLk5wvrL5RgMJU:-KWEmsoLk5wvrL5RgMJV:bsobsc1) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/abd99a79473fecaec705493a315ed08ce9be6ad4/byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m#L337)):*
> ```objc
>         }
>         
>         if (buildingFound) {
> ```

It looks like we remove this part... Is there a reason we don't need it?

---

*[byuSuite/Apps/RestroomLocator/RestroomLocator.storyboard, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEn8ZJ5cNkF72U3Bf-:-KWEn8ZJ5cNkF72U3Bf0:b-il07vp) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocator.storyboard#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

Rename this to Restrooms.storyboard

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorBuildingSelectionViewController.h, line 16 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEnFNn3QjXEC077ilR:-KWEnFNn3QjXEC077ilS:b-o2znm3) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorBuildingSelectionViewController.h#L16)):*
> ```objc
> @protocol ByuRestroomBuildingSelectionDelegate <NSObject>
> 
> - (void) updateSelectedBuilding:(CampusBuilding*) building;
> ```

Add space after CampusBuilding

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m, line 87 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEopeYwrF5F5lT5_1n:-KWEopeYwrF5F5lT5_1o:b-jythdl) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m#L87)):*
> ```objc
>         //user has authorized feature to use location services
>         [self.locationManager startUpdatingLocation];
>         [self loadClosestBuildingToUserLocation];
> ```

Is this a duplicate of above? Are we loading twice?

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m, line 104 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFWB4dLTSw0mIDI9IQ:-KWEozQVIGWrBu4LFgkC:bjb1j3b) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m#L104)):*
> ```objc
> - (void)createRestroomsSucceeded:(ByuRestrooms *)restrooms
> {
>     self.successfulCallbackCounter++;
> ```

I think we can do this without a counter. Just check to see if both are loaded in the loadDataIfReady

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m, line 121 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFPOa5dFhjQBQp1hEQ:-KWFPOa5dFhjQBQp1hER:b-1l79zs) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m#L121)):*
> ```objc
> 
> //Called in four different places in the code, but really only ever called once when the view loads.
> //It shows up so many times in this file to ensure all prerequisite data has been loaded prior to this function call.
> ```

Is this comment still true even though you changed the loading logic?

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m, line 219 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFV6qQPPQ8pTKN9OM1:-KWFV6qQPPQ8pTKN9OM2:b3xc04c) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m#L219)):*
> ```objc
> -(void)configureLocationManager {
>     self.locationManager = [[CLLocationManager alloc] init];
>     self.locationManager.delegate = self;
> ```

Do we need to be a delegate and start updating location? Or can we just requestWhenInUseAuth?

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m, line 265 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFWJEZnVYerAyq4Kmf:-KWFWJEZnVYerAyq4Kmg:ba1ptyy) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m#L265)):*
> ```objc
> -(void)loadDataIfReady {
>     //decrement for each successful callback that has been recieved
>     if (--self.successfulCallbackCounter == 0) {
> ```

Instead of using a counter here, just check if both objects are non-nil

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsHelper.m, line 35 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFWbhsO0vwSYGYTQH5:-KWFWbhsO0vwSYGYTQH6:bhzz7b3) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsHelper.m#L35)):*
> ```objc
>                     //obj has the function
>                     
>                     /*
> ```

So did we decide that IMP was the best way to go? For some reason I thought we were leaning the other way...

By the way the comment looks great! :p

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29)*

**Comment by nateyj** [comment]
Review status: 11 of 12 files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m, line 297 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEmZwwCFOz_hI1a5A6:-KWJ5flYrj_Myunux-2x:b-mhfzc3) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m#L297)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Is there a difference on iPad
</details>
The deltas, or zoom, for iPad are larger than for the iPhone and the setMapZoomForIpad: changes deltas to look the best depending on whether it's landscape or portrait mode. -zoomToFitMapAnnotationsWithUserLocation: just shows BYU campus with no specific level for zoom, just whatever fits best.

---

*[byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m, line 337 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEmsoLk5wvrL5RgMJU:-KWJ78M5JxNn_nSpXLf6:b-2r1irf) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/abd99a79473fecaec705493a315ed08ce9be6ad4/byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m#L337)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> It looks like we remove this part... Is there a reason we don't need it?
</details>
I'm not sure what part you're talking about, the -loadData? Line 342 is just an empty line

---

*[byuSuite/Apps/RestroomLocator/RestroomLocator.storyboard, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEn8ZJ5cNkF72U3Bf-:-KWJCC9G5Idq-4RCdnBC:b-c4lqfb) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocator.storyboard#L1)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Rename this to Restrooms.storyboard
</details>
Will do after this code review

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorBuildingSelectionViewController.h, line 16 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEnFNn3QjXEC077ilR:-KWJ7TraT_Ho_mWhegzj:b-acrxa9) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorBuildingSelectionViewController.h#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Add space after CampusBuilding
</details>
I haven't formatted anything yet, so you could see the changes as clearly as possible, but I definitely will after this code review

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m, line 87 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEopeYwrF5F5lT5_1n:-KWJ8VfrWy7BtEpy5RZ1:bpj0kgh) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m#L87)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Is this a duplicate of above? Are we loading twice?
</details>
Nope. -loadClosestBuildingToUserLocation checks if self.buildingWithRestrooms has been loaded or not. If it hasn't yet, then the method does nothing. The first time -locationManager:didChangeAuthorizationStatus: is called, self.buildingsWithRestrooms usually hasn't been loaded yet and so it won't do anything. The main reason -loadClosestBuildingToUserLocation is in -locationManager:didChangeAuthorizationStatus: is because if the user turns off location services and then turns it back on, -locationManager:didChangeAuthorizationStatus: will be triggered and the user could be in a new location, so I figured we could find the closest building with restrooms to them.

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m, line 104 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFWB4dLTSw0mIDI9IQ:-KWJAIuFl3f2mITUGp6g:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m#L104)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> I think we can do this without a counter. Just check to see if both are loaded in the loadDataIfReady
</details>
Done.

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m, line 121 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFPOa5dFhjQBQp1hEQ:-KWJAYkm4VpUcaT4v3d_:b-q3pu4t) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m#L121)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Is this comment still true even though you changed the loading logic?
</details>
It shows up three times in the file. It gets called once if the user doesn't change their location services authorization. Whenever the authorization changes, it will get called. Would you like me to scrap the comment?

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m, line 219 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFV6qQPPQ8pTKN9OM1:-KWJBO37q1woWpwQG67B:b5u7twy) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m#L219)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Do we need to be a delegate and start updating location? Or can we just requestWhenInUseAuth?
</details>
I believe we do need to be a delegate, because in order to show the closest building with restrooms to the user, we need the user's location, which means we need to be a delegate and get their location. Once we get the user's location, we stop updating their location. This logic is in -locationManager:didUpdateLocations: and explained in the comment above it

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m, line 265 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFWJEZnVYerAyq4Kmf:-KWJBl0NE3r406RU-4C0:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m#L265)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Instead of using a counter here, just check if both objects are non-nil
</details>
Done.

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsHelper.m, line 35 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFWbhsO0vwSYGYTQH5:-KWJBoFPP4MA2Ki6YS5T:b-bl59ak) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsHelper.m#L35)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> So did we decide that IMP was the best way to go? For some reason I thought we were leaning the other way...
> 
> By the way the comment looks great! :p
</details>
Yes we decided IMP was the way to go. If you'll allow suppressing a warning then we can do that instead. It's easier to tell what's going on when the warning is being suppressed. I'm honestly not sure which is the best way to go. They both "suppress" the warning

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m, line 297 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEmZwwCFOz_hI1a5A6:-KWJOHPqKZxFiXQFitil:bt8htgq) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m#L297)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary>
> The deltas, or zoom, for iPad are larger than for the iPhone and the setMapZoomForIpad: changes deltas to look the best depending on whether it's landscape or portrait mode. -zoomToFitMapAnnotationsWithUserLocation: just shows BYU campus with no specific level for zoom, just whatever fits best.
</details>
Let's test it and possibly get rid of it

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m, line 121 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFPOa5dFhjQBQp1hEQ:-KWJLW-Nqk2XSIO6mqEG:bro6ikr) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m#L121)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary>
> It shows up three times in the file. It gets called once if the user doesn't change their location services authorization. Whenever the authorization changes, it will get called. Would you like me to scrap the comment?
</details>
I think so. Unless there's any info in it to explain how to use it. I think the number of times it's called the programmer can figure out on their own

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsHelper.m, line 35 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFWbhsO0vwSYGYTQH5:-KWJNqS2HwwWYd7bPFbq:b57x13q) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsHelper.m#L35)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary>
> Yes we decided IMP was the way to go. If you'll allow suppressing a warning then we can do that instead. It's easier to tell what's going on when the warning is being suppressed. I'm honestly not sure which is the best way to go. They both "suppress" the warning
</details>
Let's use the suppress warning. Sorry. :-/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29)*

**Comment by nateyj** [comment]
Review status: 5 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m, line 297 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEmZwwCFOz_hI1a5A6:-KWJY5AaBMt0IY4NQWDG:bvdltxk) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/MapMyClasses/controller/MapMyClassesViewController.m#L297)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Let's test it and possibly get rid of it
</details>
got rid of it

---

*[byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m, line 121 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFPOa5dFhjQBQp1hEQ:-KWJSKay9_uaY7ysnr_W:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/RestroomLocator/RestroomLocatorRootViewController.m#L121)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> I think so. Unless there's any info in it to explain how to use it. I think the number of times it's called the programmer can figure out on their own
</details>
Done.

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsHelper.m, line 35 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWFWbhsO0vwSYGYTQH5:-KWJSCiWeFDkbcd6ZxcK:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsHelper.m#L35)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Let's use the suppress warning. Sorry. :-/
</details>
Done.

---

*[byuSuite/Apps/DepartmentDirectory/controller/DepartmentDirectoryListingViewController.m, line 215 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29#-KWEmk3BYOj_dhz18orq:-KWJmK37T-yzHOpQ8Whv:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e4d35a8c662dc3b9e0f26473e76421b7ae6cec3f/byuSuite/Apps/DepartmentDirectory/controller/DepartmentDirectoryListingViewController.m#L215)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Remove TODO and solve it
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29)*

**Comment by romrell4** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/29)*

**Pull request merged**
