### PR TITLE
hotfix/restrooms

### PR DESCRIPTION
**Pull request by nateyj**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/40)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHxbpz2Zd1P9DoTVTg:-KXHxbq-pqopcpKX-pRO:b7sxtch) (no related file):*
Remove Table from controller names

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHxeYxVHWZslbdOHow:-KXHxeYxVHWZslbdOHox:b-5dal0n) (no related file):*
Reorder stuff in groups

---

*[byuSuite/Apps/Restrooms/controller/RestroomsBuildingsTableViewController.m, line 124 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI31y_e_G8FpugmeSV:-KXI31y_e_G8FpugmeSW:b-o9fpxz) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsBuildingsTableViewController.m#L124)):*
> ```objc
>     
>     //NOTE: using the index constant requires that the constant's index matches what shows in the storyboard
>     ((RestroomsTableViewController *)self.tabBarController.viewControllers[NEAR_ME_VC_INDEX]).building = [self.buildingsMatchingSearchText objectAtIndex:indexPath.row];
> ```

Instead of objectAtIndex, use []

---

*[byuSuite/Apps/Restrooms/controller/RestroomsMapViewController.m, line 34 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI1628QHfjSg7akdOo:-KXI1629ZBU6JrTfx6gD:b-votjjj) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsMapViewController.m#L34)):*
> ```objc
>     [super viewWillAppear:animated];
>     
>     self.tabBarController.title = @"Map";
> ```

I think we can do this from the storyboard

---

*[byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m, line 58 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHzHCctP27I83PMlhW:-KXHzHCdg6w9ahDZl_rg:bcrlkd8) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m#L58)):*
> ```objc
>     [super viewWillAppear:animated];
>     
>     self.tabBarController.delegate = self;
> ```

Move this to viewDidLoad if you can't do it from the storyboard

---

*[byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m, line 217 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI-ouqtFYxTYGhMw2M:-KXI-ouqtFYxTYGhMw2N:b-qirzz6) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m#L217)):*
> ```objc
>     NSString *room;
>     
>     if (restroom.room.intValue > 0) {
> ```

Check for maybe ternary here?

---

*[byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m, line 222 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI-8jdsTfXNS11pHN5:-KXI-8jdsTfXNS11pHN6:b2u5rmb) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m#L222)):*
> ```objc
>     } else {
>         //first character is not a number
>         room = [restroom.room substringFromIndex:1];
> ```

Instead find the first numeric character

---

*[byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m, line 260 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI0IYvlfllHybSlUJO:-KXI0IYvlfllHybSlUJP:btmxxf6) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m#L260)):*
> ```objc
> }
> 
> -(void)groupRestroomsByFloor {
> ```

Reorder all functions

---

*[byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m, line 339 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHyix3H4QD_jiBy-Ij:-KXHyix3H4QD_jiBy-Ik:br2526n) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m#L339)):*
> ```objc
>     if (self.buildings && self.restrooms) {
>         //get all of the buildings that have restrooms
>         self.buildingsWithRestrooms = [NSMutableArray arrayWithArray:[CampusLocationsHelper filterBuildings:self.buildings withObjects:self.restrooms respondingToSelector:@selector(building)]];
> ```

Remove NSMutableArray

---

*[byuSuite/Apps/Restrooms/view/Restrooms.storyboard, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI3Jnq9cgHlJx7PuM2:-KXI3Jnq9cgHlJx7PuM3:b-mvv0tv) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/view/Restrooms.storyboard#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

Drag the search bar above the tableView in the buildings VC. It will also make it look prettier

---

*[byuSuite/Apps/Restrooms/view/RestroomsBuildingTableViewCell.h, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHt5cv--0FmFT9K_Vj:-KXHt5cwcXeHAyKO_ffQ:b5khezd) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/view/RestroomsBuildingTableViewCell.h#L14)):*
> ```objc
> 
> @property (weak, nonatomic) IBOutlet UILabel *rightDetailTextLabel;
> @property (weak, nonatomic) IBOutlet UILabel *subtitleTextLabel;
> ```

Reorder these

---

*[byuSuite/Apps/Restrooms/view/RestroomsBuildingTableViewCell.m, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHtEvkJM4jfx3kOMzF:-KXHtEvkJM4jfx3kOMzG:b-6y112n) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/view/RestroomsBuildingTableViewCell.m#L14)):*
> ```objc
> @implementation RestroomsBuildingTableViewCell
> 
> -(void)awakeFromNib {
> ```

Check if there's a new one

---

*[byuSuite/Apps/Restrooms/view/RestroomsBuildingTableViewCell.m, line 17 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI1d2TDLTcWNwDq9-w:-KXI1d2TDLTcWNwDq9-x:b-hwh1g1) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/view/RestroomsBuildingTableViewCell.m#L17)):*
> ```objc
>     [super awakeFromNib];
>     
>     _subtitleTextLabel.textColor = [UIColor byuDetailTextColor];
> ```

I think you can use self.subtitleTextLabel here

---

*[byuSuite/Apps/Restrooms/view/RestroomsNearMeTableViewCell.h, line 13 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHtLDpysYESngFiw2K:-KXHtLDpysYESngFiw2L:b-x3f89m) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/view/RestroomsNearMeTableViewCell.h#L13)):*
> ```objc
> @interface RestroomsNearMeTableViewCell : UITableViewCell
> 
> @property (weak, nonatomic) IBOutlet UILabel *rightDetailTextLabel;
> ```

Swap order

---

*[byuSuite/Apps/Restrooms/view/RestroomsNearMeTableViewCell.m, line 17 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI1jTSZVX7bvxnX-Cl:-KXI1jTSZVX7bvxnX-Cm:b-fntgle) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/view/RestroomsNearMeTableViewCell.m#L17)):*
> ```objc
>     [super awakeFromNib];
>     
>     _rightDetailTextLabel.textColor = [UIColor byuDetailTextColor];
> ```

Use self.rightDetailTextLabel

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 483 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHtTB7n4S732VuDSfX:-KXHtTB7n4S732VuDSfY:b-1jydlc) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/f8e02824756e5eaf734f29a0a45e9b4849d18efa/byuSuite/byuSuite.xcodeproj/project.pbxproj#L483)):*
> ```
> 		3CAE39A819BE2EBD0009A080 /* RestroomLocatorBuildingSelectionViewController.m in Sources */ = {isa = PBXBuildFile; fileRef = 8684D070199179B100D71302 /* RestroomLocatorBuildingSelectionViewController.m */; };
> 		3CAE39A919BE2EBD0009A080 /* RestroomLocatorRootViewController.m in Sources */ = {isa = PBXBuildFile; fileRef = 8684D072199179B100D71302 /* RestroomLocatorRootViewController.m */; };
> 		3CAE39AC19BE2EBD0009A080 /* BYUCougarCashTransactions.m in Sources */ = {isa = PBXBuildFile; fileRef = 8694F13F195A2EE100F47DC2 /* BYUCougarCashTransactions.m */; };
> ```

Test cougar cash and see if it's working

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 3255 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHuHV_9R_KPN5T28Ta:-KXHuHV_9R_KPN5T28Tb:b-2x3d42) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/byuSuite.xcodeproj/project.pbxproj#L3255)):*
> ```
> 				8D1107310486CEB800E47090 /* byuSuite-Info.plist */,
> 				758EC9FB13871B88002A98B7 /* img */,
> 				03F3DCC11D26D1250026124C /* map.png */,
> ```

Make 2x and 3x versions and put into images.xcassets

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusBuilding.m, line 13 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHvbBcEby7sJ-9fL-u:-KXHvbBcEby7sJ-9fL-v:ba3dfna) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Classes/ReusableClients/CampusLocations/CampusBuilding.m#L13)):*
> ```objc
> #import "NSString+BYUAdditions.h"
> 
> #define FEET_PER_METERS 3.28084
> ```

Remove?

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m, line 17 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHw60MDZkX5nLC5HKt:-KXHw60NlqEm9aZTh8d6:b-ljsldk) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m#L17)):*
> ```objc
> 
> +(void)loadCampusBuildingsWithCallback:(CampusBuildingsCallback)callback {
>     NSURL *url = [self urlWithBaseUrl:[NSString stringWithFormat:@"%@/building?additionalOnly=true", BASE_URL]];
> ```

Use urlWithBaseUrl...path...query...

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m, line 55 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHwDkl9rNqobI7NOTg:-KXHwDkl9rNqobI7NOTh:b-kn5jsr) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m#L55)):*
> ```objc
>         } else {
>             NSDictionary *responseDict = [response getDataJson];
>             NSMutableArray<Restroom *> *restrooms = [NSMutableArray array];
> ```

Use transform in both functions

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m, line 58 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHwbhEQFTqtpnP0Pio:-KXHwbhEQFTqtpnP0Pip:b-pottot) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m#L58)):*
> ```objc
>             
>             for (NSDictionary *restroomDict in responseDict[@"room"]) {
>                 Restroom *restroom = [Restroom createRestroomFromDictionary:restroomDict];
> ```

rename to restroomWithDictionary

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsHelper.h, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHwzu7RSqLrvolXwEN:-KXHwzu7RSqLrvolXwEO:b5jo4fw) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsHelper.h#L23)):*
> ```objc
>  *  buildings:  list of buildings to filter
>  */
> +(NSArray<CampusBuilding *> *)buildingsMatchingSearchText:(NSString *)searchText withBuildings:(NSArray<CampusBuilding *> *)buildings;
> ```

Remove redundant buildings on any functions in here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40)*

**Comment by nateyj** [comment]
Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHxbpz2Zd1P9DoTVTg:-KXkhNLcmJ1a_-gHncIg:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove Table from controller names
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHxeYxVHWZslbdOHow:-KXkhOhYa5-mJ5zb4pOT:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Reorder stuff in groups
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/controller/RestroomsBuildingsTableViewController.m, line 124 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI31y_e_G8FpugmeSV:-KXkhJp3_2hc7SB0IgWw:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsBuildingsTableViewController.m#L124)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Instead of objectAtIndex, use []
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/controller/RestroomsMapViewController.m, line 34 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI1628QHfjSg7akdOo:-KXl9hWJ7h_c067Z_FQB:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsMapViewController.m#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think we can do this from the storyboard
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m, line 58 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHzHCctP27I83PMlhW:-KXkkZAb50f1X9cB3MYf:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m#L58)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Move this to viewDidLoad if you can't do it from the storyboard
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m, line 217 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI-ouqtFYxTYGhMw2M:-KXkt0NsQx6-HA7JNQuu:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m#L217)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Check for maybe ternary here?
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m, line 222 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI-8jdsTfXNS11pHN5:-KXkt1J3snvVxBqKe8W0:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m#L222)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Instead find the first numeric character
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m, line 260 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI0IYvlfllHybSlUJO:-KXkt3CpUCukAkth8qDm:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m#L260)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Reorder all functions
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m, line 339 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHyix3H4QD_jiBy-Ij:-KXktG3p3j7IIVcwVOKL:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/controller/RestroomsTableViewController.m#L339)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove NSMutableArray
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/view/Restrooms.storyboard, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI3Jnq9cgHlJx7PuM2:-KXkuJKuDpSxkMWaPrmB:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/view/Restrooms.storyboard#L1)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Drag the search bar above the tableView in the buildings VC. It will also make it look prettier
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/view/RestroomsBuildingTableViewCell.h, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHt5cv--0FmFT9K_Vj:-KXkuWmHO4fuAjz6T_dy:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/view/RestroomsBuildingTableViewCell.h#L14)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Reorder these
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/view/RestroomsBuildingTableViewCell.m, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHtEvkJM4jfx3kOMzF:-KXl-EGtW8dO2zLqQxBY:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/view/RestroomsBuildingTableViewCell.m#L14)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Check if there's a new one
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/view/RestroomsBuildingTableViewCell.m, line 17 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI1d2TDLTcWNwDq9-w:-KXl-FIa3KLHaBdSv_iX:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/view/RestroomsBuildingTableViewCell.m#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think you can use self.subtitleTextLabel here
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/view/RestroomsNearMeTableViewCell.h, line 13 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHtLDpysYESngFiw2K:-KXl-LWbG4-28WZXi0NK:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/view/RestroomsNearMeTableViewCell.h#L13)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Swap order
</blockquote></details>

Done.

---

*[byuSuite/Apps/Restrooms/view/RestroomsNearMeTableViewCell.m, line 17 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXI1jTSZVX7bvxnX-Cl:-KXl-MnFpaeO8o9DclR5:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Apps/Restrooms/view/RestroomsNearMeTableViewCell.m#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use self.rightDetailTextLabel
</blockquote></details>

Done.

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 483 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHtTB7n4S732VuDSfX:-KXl-OKVHp5WAj626YCp:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/f8e02824756e5eaf734f29a0a45e9b4849d18efa/byuSuite/byuSuite.xcodeproj/project.pbxproj#L483)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Test cougar cash and see if it's working
</blockquote></details>

Done.

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusBuilding.m, line 13 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHvbBcEby7sJ-9fL-u:-KXl-yUlmjM8QOf7zklD:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Classes/ReusableClients/CampusLocations/CampusBuilding.m#L13)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m, line 17 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHw60MDZkX5nLC5HKt:-KXl4vCxZYBZSzg2bPQG:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use urlWithBaseUrl...path...query...
</blockquote></details>

Done.

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m, line 55 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHwDkl9rNqobI7NOTg:-KXl33cIbUKWE-8yvXU_:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m#L55)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use transform in both functions
</blockquote></details>

Done.

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m, line 58 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHwbhEQFTqtpnP0Pio:-KXl5DHEfnX7qypltKZV:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m#L58)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

rename to restroomWithDictionary
</blockquote></details>

Done.

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsHelper.h, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHwzu7RSqLrvolXwEN:-KXl6QM7AJMpjbEXS5LJ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsHelper.h#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove redundant buildings on any functions in here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40)*

**Comment by romrell4** [comment]
Reviewed 23 of 24 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m, line 58 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHwbhEQFTqtpnP0Pio:-KXlHN5VU7-ZFum9llSP:bx7un04) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m#L58)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Let's do restroomWithDictionary instead of createRestroomWithDictionary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40)*

**Comment by nateyj** [comment]
Review status: 44 of 47 files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m, line 58 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHwbhEQFTqtpnP0Pio:-KXlJvP1yUUgUGBhfdd9:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/Classes/ReusableClients/CampusLocations/CampusLocationsClient.m#L58)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's do restroomWithDictionary instead of createRestroomWithDictionary
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40)*

**Comment by romrell4** [comment]
Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40)*

**Comment by romrell4** [comment]
Reviewed 19 of 22 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40)*

**Comment by nateyj** [comment]
Review status: 56 of 57 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/byuSuite.xcodeproj/project.pbxproj, line 3255 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40#-KXHuHV_9R_KPN5T28Ta:-KXvwF1uOKte2AStJwdD:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/1b7e114ae8c9e05a28a01bb10af7230d3babe7e3/byuSuite/byuSuite.xcodeproj/project.pbxproj#L3255)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Make 2x and 3x versions and put into images.xcassets
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40)*

**Comment by romrell4** [comment]
Reviewed 1 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/40)*

**Pull request merged**
