### PR TITLE
Fixed lag on login

### PR DESCRIPTION
**Pull request by romrell4**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/121)

### CODE REVIEW

**Comment by ecbrady** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m, line 244 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/121#-KeK-rjjdpVEoZuImcHZ:-KeK-rjjdpVEoZuImcH_:b-5yjj9v) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/82d4f83370f8b59a9d16628d66211aae8a5b1266/byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m#L244)):*
> ```objc
>         [self.spinner stopAnimating];
>         
>         //This is not synchronous, because in order to load features, categories, favorites, and the what's new - we need to check if the person's GRO groups
> ```

"check if the person's GRO groups" seems either incomplete or does not need the if.

---

*[byuSuite/Classes/MainScreen/MainStoryboard.storyboard, line 28 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/121#-KeK0MxCt9FRTxbBdVGR:-KeK0MxCt9FRTxbBdVGS:bv6ml4b) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/82d4f83370f8b59a9d16628d66211aae8a5b1266/byuSuite/Classes/MainScreen/MainStoryboard.storyboard#L28)):*
> ```XML
>                                 <rect key="frame" x="0.0" y="64" width="375" height="24"/>
>                                 <subviews>
>                                     <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="Loading Credentials..." textAlignment="natural" lineBreakMode="tailTruncation" baselineAdjustment="alignBaselines" adjustsFontSizeToFit="NO" translatesAutoresizingMaskIntoConstraints="NO" id="k8n-xX-gYF">
> ```

What if they are not logged in? Will this still handle that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/121)*

**Comment by ecbrady** [comment]
When I run it not logged in, it sits spinning indefinitely displaying Loading Credentials...

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/121#-:-KeK19kGbV_KdMp1S4-k:bcg1xe2)*

**Comment by romrell4** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m, line 244 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/121#-KeK-rjjdpVEoZuImcHZ:-KeK17nhcORgmSzIyhpt:b6fuimn) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/82d4f83370f8b59a9d16628d66211aae8a5b1266/byuSuite/Classes/MainScreen/MainScreenFavoritesViewController.m#L244)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

"check if the person's GRO groups" seems either incomplete or does not need the if.
</blockquote></details>

I'll fix that

---

*[byuSuite/Classes/MainScreen/MainStoryboard.storyboard, line 28 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/121#-KeK0MxCt9FRTxbBdVGR:-KeK115QypDQuCuxjNsG:bmn7usp) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/82d4f83370f8b59a9d16628d66211aae8a5b1266/byuSuite/Classes/MainScreen/MainStoryboard.storyboard#L28)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

What if they are not logged in? Will this still handle that?
</blockquote></details>

I believe so. If you see the line in the vewDidLoad of the FavoritesActivity

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/121)*

**Comment by romrell4** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/MainScreen/MainStoryboard.storyboard, line 28 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/121#-KeK0MxCt9FRTxbBdVGR:-KeK2gsx38eIuXHiJpMQ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/82d4f83370f8b59a9d16628d66211aae8a5b1266/byuSuite/Classes/MainScreen/MainStoryboard.storyboard#L28)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I believe so. If you see the line in the vewDidLoad of the FavoritesActivity
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/121)*

**Comment by ecbrady** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/121#-:-KeK3GgQmG_WwV6jOSHo:bnfp4nl)*

**Pull request merged**
