### PR TITLE
Hotfix/ls

### PR DESCRIPTION
**Pull request by nateyj**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/138)

### CODE REVIEW

**Comment by romrell4** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_QRB7SYORBFPRh_vf:-Kg_QRB7SYORBFPRh_vg:b-ojibva) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L14)):*
> ```objc
> 
> #define BASE_URL @"https://learningsuite.byu.edu"
> #define BASE_LS_FILE_URL @"https://learningsuite.byu.edu/plugins/Upload/fileDownload.php?fileId"
> ```

It looks like this isn't used... Is that the case?

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_XyYsxCwWvp_H9z3r:-Kg_XyYsxCwWvp_H9z3s:b-v33apv) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L18)):*
> ```objc
> @interface LSWebViewController () <UIDocumentInteractionControllerDelegate>
> 
> @property (nonatomic) UIBarButtonItem *actionButton;
> ```

We might not have to save this as a property. Just use navigationItem.rightBarButtonItem instead

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_YJmiZcEAhpZNNSxu:-Kg_YJmiZcEAhpZNNSxv:b3xrav3) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L19)):*
> ```objc
> 
> @property (nonatomic) UIBarButtonItem *actionButton;
> @property (nonatomic) NSURL *downloadedFileURL; //URL of most recently downloaded file (for caching)
> ```

Could you explain to me how the cacheing is working? It seems that we clear out the cache every time a load is begun...

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 112 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_Z1FienZ1ltHnTuPn:-Kg_Z1FienZ1ltHnTuPo:bvzrquu) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L112)):*
> ```objc
>     } else {
>         [self.spinner startAnimating];
>         [[[NSURLSession sharedSession] downloadTaskWithRequest:self.request completionHandler:^(NSURL * _Nullable location, NSURLResponse * _Nullable response, NSError * _Nullable error) {
> ```

I'm wondering if we should add this to the ByuRequest object... That way LearningSuite wouldn't have to have any boiler plate code and we could reuse this stuff if any other feature wanted to download. What are your thoughts?

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 118 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_ZInXBpTMa6_r4COh:-Kg_ZInXBpTMa6_r4COi:b-1ohigu) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L118)):*
> ```objc
>                 
>                 if (error) {
>                     [self showError:nil withTitle:@"Unable to Download File" andCallback:nil];
> ```

Do we want a nil callback? What would the user see if there was an error?

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 120 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_ZOWqVX97YGFkUlQP:-Kg_ZOWqVX97YGFkUlQQ:bo7pcxp) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L120)):*
> ```objc
>                     [self showError:nil withTitle:@"Unable to Download File" andCallback:nil];
>                 } else {
>                     NSString *documentDirectoryPath = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) firstObject];
> ```

What is the user domain mask? Comment above this line about what it is doing

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 144 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_Yh7zYSyFNruTCWc8:-Kg_YWVciSbtM6gaPdPa:b-11w4q) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L144)):*
> ```objc
>                         }
>                     } else {
>                         if ([fileManager moveItemAtURL:location toURL:self.downloadedFileURL error:nil]) {
> ```

It looks like there's a lot of duplicate logic here. Could we just remove what is there and then always move? If not, this logic is fine. It seems that we could do something like this:

```
// Remove file at self.downloadedFileURL

if (Move from location to self.downloadedFileURL) {
  [self presentDocumentInteractionControllerWithURL:self.downloadedFileURL];
} else {
  [self showError:nil withTitle:@"Unable to Download File" andCallback:nil];
}
```

Then you might even be able to inline `presentDocument...` if you'd like. Maybe not though, since this method is sorta long...

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 157 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg__iMWVqEVxVtbN4Ga:-Kg__iMWVqEVxVtbN4Gb:bf6ga5w) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L157)):*
> ```objc
> 
> -(void)presentDocumentInteractionControllerWithURL:(NSURL *)url {
>     if ([[NSFileManager defaultManager] fileExistsAtPath:url.path]) {
> ```

Didn't we already check this with the move?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138)*

**Comment by nateyj** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_QRB7SYORBFPRh_vf:-Kg__xx1sVVkZBHsBxM6:bgn7958) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L14)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

It looks like this isn't used... Is that the case?
</blockquote></details>

Yep. That was in there from something I was testing earlier. Good find

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_XyYsxCwWvp_H9z3r:-Kg_avZDVcL9ysoF5VSU:b-f9hyn8) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

We might not have to save this as a property. Just use navigationItem.rightBarButtonItem instead
</blockquote></details>

Yep. Removed it

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_YJmiZcEAhpZNNSxu:-Kg_b8nJvSP_u5yi4g64:b-beidfs) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L19)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Could you explain to me how the cacheing is working? It seems that we clear out the cache every time a load is begun...
</blockquote></details>

Yes, the cached file is only if they press the button, decide to cancel, then decide they want to look at their options again. I had it reset every time a new request begins in case they navigate to something else that would be saved. Do you want to just removing the caching and just download the file new every time they click on the action button?

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 112 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_Z1FienZ1ltHnTuPn:-Kg_bUPKOzpHJo7CXiZm:bkkfz7i) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L112)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I'm wondering if we should add this to the ByuRequest object... That way LearningSuite wouldn't have to have any boiler plate code and we could reuse this stuff if any other feature wanted to download. What are your thoughts?
</blockquote></details>

I actually found out a way to save the file without using -downloadTaskWithRequest:completionHandler: and using ByuRequest instead!

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 118 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_ZInXBpTMa6_r4COh:-Kg_b_Tg7VH2Ayo495_2:b-rbsjk7) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L118)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we want a nil callback? What would the user see if there was an error?
</blockquote></details>

Just the error alert with the title above and then when they press OK it would keep them viewing the file instead of jumping back to the list of content. It's just an error with downloading it the second time to give them options of how to view it

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 120 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_ZOWqVX97YGFkUlQP:-Kg_cKHewwhCu0wRtJt9:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L120)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is the user domain mask? Comment above this line about what it is doing
</blockquote></details>

Done.

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 144 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg_Yh7zYSyFNruTCWc8:-Kg_cSJLk4o6cT-9wRpv:bpjoy3d) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L144)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

It looks like there's a lot of duplicate logic here. Could we just remove what is there and then always move? If not, this logic is fine. It seems that we could do something like this:

```
// Remove file at self.downloadedFileURL

if (Move from location to self.downloadedFileURL) {
  [self presentDocumentInteractionControllerWithURL:self.downloadedFileURL];
} else {
  [self showError:nil withTitle:@"Unable to Download File" andCallback:nil];
}
```

Then you might even be able to inline `presentDocument...` if you'd like. Maybe not though, since this method is sorta long...

</blockquote></details>

See comment above about now using ByuRequest. Switching to using that eliminated this issue

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 157 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-Kg__iMWVqEVxVtbN4Ga:-Kg_d2UOTHlChcIViLt3:b-33b6k6) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/a019495893378069db7ac6f98918350b6d28b244/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L157)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Didn't we already check this with the move?
</blockquote></details>

See comment above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 119 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-KgaiD0v_UcENLDujckN:-KgaiD0v_UcENLDujckO:b-b2bub7) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/93ad4bfc77ca0c0269c2dd8b81a7877e89258610/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L119)):*
> ```objc
>             
>             if ([fileManager fileExistsAtPath:downloadedFileURL.path]) {
>                 if (![fileManager removeItemAtURL:downloadedFileURL error:nil]) {
> ```

I don't think we need the check here. If it didn't remove anything, that's probably okay to ignore, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138)*

**Comment by nateyj** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/LearningSuite/controller/LSWebViewController.m, line 119 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138#-KgaiD0v_UcENLDujckN:-Kgt_c33Sl6aClguu1rn:b-dcrtm7) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/93ad4bfc77ca0c0269c2dd8b81a7877e89258610/byuSuite/Apps/LearningSuite/controller/LSWebViewController.m#L119)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I don't think we need the check here. If it didn't remove anything, that's probably okay to ignore, right?
</blockquote></details>

True. I got rid of it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/138)*

**Pull request merged**
