### PR TITLE
Hotfix/person directory

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/92)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 13 of 16 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 333 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92#-Kc-Z356Hfc7UvZ6MmOC:-Kc-Z356Hfc7UvZ6MmOD:bwk5nda) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/2b0f69ed590f709e1ab4324c143260ca5e2ec74e/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L333)):*
> ```objc
>             break;
>         case 3:
>             searchEngineString = ENGINE_BOTH;
> ```

We removed the modifier here. Does that change anything?

---

*[byuSuite/Apps/PersonDirectory/model/PersonDirectoryClient.m, line 29 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92#-Kc-ZF1YgG_tG6s-1cd_:-Kc-ZF1YgG_tG6s-1cda:b-i027mb) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/2b0f69ed590f709e1ab4324c143260ca5e2ec74e/byuSuite/Apps/PersonDirectory/model/PersonDirectoryClient.m#L29)):*
> ```objc
>     [request startAsynchronousWithCompletionHandler:^(ByuResponse *response) {
>         if (response.error) {
>             if (response.response.statusCode == 404) {
> ```

Comment above this line

---

*[byuSuite/Apps/PersonDirectory/model/PersonDirectoryPerson.m, line 17 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92#-Kc-ZO_eeboObe5Aci2o:-Kc-ZO_eeboObe5Aci2p:b-6sy49m) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/2b0f69ed590f709e1ab4324c143260ca5e2ec74e/byuSuite/Apps/PersonDirectory/model/PersonDirectoryPerson.m#L17)):*
> ```objc
> 
> +(PersonDirectoryPerson *)personWithDictionary:(NSDictionary *)dictionary {
>     PersonDirectoryPerson *me = [[PersonDirectoryPerson alloc] init];
> ```

[[self alloc] init] instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92)*

**Comment by ecbrady** [comment]
Review status: 14 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 333 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92#-Kc-Z356Hfc7UvZ6MmOC:-Kc-_618Dwo9jW3jpM2z:bplonel) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/2b0f69ed590f709e1ab4324c143260ca5e2ec74e/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L333)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

We removed the modifier here. Does that change anything?
</blockquote></details>

I extracted them out since it's doing the same in all but case 3. I use the turnery to make up for that.

---

*[byuSuite/Apps/PersonDirectory/model/PersonDirectoryClient.m, line 29 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92#-Kc-ZF1YgG_tG6s-1cd_:-Kc-_TQ0i9kraP-4JJMg:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/2b0f69ed590f709e1ab4324c143260ca5e2ec74e/byuSuite/Apps/PersonDirectory/model/PersonDirectoryClient.m#L29)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment above this line
</blockquote></details>

Done.

---

*[byuSuite/Apps/PersonDirectory/model/PersonDirectoryPerson.m, line 17 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92#-Kc-ZO_eeboObe5Aci2o:-Kc-_vStGLnuMqSKS0FC:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/2b0f69ed590f709e1ab4324c143260ca5e2ec74e/byuSuite/Apps/PersonDirectory/model/PersonDirectoryPerson.m#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

[[self alloc] init] instead
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 333 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92#-Kc-Z356Hfc7UvZ6MmOC:-Kc-biaB7GkBl7-F9__v:bcn82xa) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/2b0f69ed590f709e1ab4324c143260ca5e2ec74e/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L333)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

I extracted them out since it's doing the same in all but case 3. I use the turnery to make up for that.
</blockquote></details>

Talk to me

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m, line 333 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92#-Kc-Z356Hfc7UvZ6MmOC:-Kc-jH0Lx9J6Y8IcrPY1:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/2b0f69ed590f709e1ab4324c143260ca5e2ec74e/byuSuite/Apps/PersonDirectory/controller/PersonDirectorySearchViewController.m#L333)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Talk to me
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/92)*

**Pull request merged**
