### PR TITLE
Swift/support

### PR DESCRIPTION
**Pull request by romrell4**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/164)

### CODE REVIEW

**Comment by ecbrady** [comment]
Reviewed 62 of 70 files at r1.
Review status: 49 of 57 files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/Alumni/controller/AlumniConnectViewController.swift, line 9 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaIcckMN69hTEZeB7n:-KiaIccl2-4kMaJX2tZj:b-npnmv5) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Apps/Alumni/controller/AlumniConnectViewController.swift#L9)):*
> ```Swift
> //
> 
> import UIKit
> ```

Are we not using Foundation then?

---

*[byuSuite/Classes/byuSuite-Bridging-Header.h, line 6 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaJtY6hytQzKYcmD23:-KiaJtY6hytQzKYcmD24:b-upi5i3) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e3144d0e0e7d1698d9f6330da6af98d28c2597f9/byuSuite/Classes/byuSuite-Bridging-Header.h#L6)):*
> ```objc
> 
> #import "ByuCredentialManager.h"
> #import <UIKit/UIKit.h>
> ```

Do we not need this anymore?

---

*[byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift, line 62 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaUr5MMNw1u0yIdCsk:-KiaUr5MMNw1u0yIdCsl:b-q3jow) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift#L62)):*
> ```Swift
>     
>     static func removeObserver(observer: ByuCredentialManagerObserver2) {
>         //TODO: Figure this out. There is no remove function
> ```

Have you figured it out yet or are you fine leaving this TODO in for now?

---

*[byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift, line 66 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaV98sskyO5y3PlPFf:-KiaV98tkuWYNF2dyzo-:bd9q1f) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift#L66)):*
> ```Swift
>     
>     static func login(username: String, password: String, token: OauthToken2) {
>         let defaults = UserDefaults.standard
> ```

I'm assuming you don't have the if !username || !password then return here anymore because you check them before ever calling this method, correct?

---

*[byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift, line 84 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaVWAo79gJG7bADarR:-KiaVWAo79gJG7bADarS:b3ugy22) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift#L84)):*
> ```Swift
>         
>         //Get their person summary information (this will also cache it)
>         _ = self.personSummary
> ```

Is this syntax correct? I don't fully understand what it's doing.

---

*[byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift, line 88 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaVe-19gGI0tIQvOBk:-KiaVe-19gGI0tIQvOBl:b7qqp49) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift#L88)):*
> ```Swift
>         //Notify the observers
>         for observer in _observers {
>             observer.loginSucceeded()
> ```

We don't need to check that the observers respond to selectors anymore?

---

*[byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift, line 95 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaVm-4_nEzufCXKWyr:-KiaVm-4_nEzufCXKWys:bx3ymqx) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift#L95)):*
> ```Swift
>         //Inform the observers that you are about to logout (MPN needs this especially so that the username and password are still set so that we can delete)
>         for observer in _observers {
>             observer.willLogout()
> ```

Again we don't need to check that the observers respond to selectors anymore?

---

*[byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift, line 109 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaVuSStqmhygRJg80s:-KiaVuSStqmhygRJg80t:b-9wj04a) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift#L109)):*
> ```Swift
>         //Notify the observers
>         for observer in _observers {
>             observer.logoutSucceeded()
> ```

Again... not trying to be obstinate, just thorough :P 

---

*[byuSuite/Classes/CredentialManager/Keychain.swift, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaWbBx1eEHDYCmM48B:-KiaWbBylD-0i0wv3nLr:b-zat8p) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/Keychain.swift#L20)):*
> ```Swift
>         ]
>         SecItemDelete(query as CFDictionary)
>         SecItemAdd(query as CFDictionary, nil)
> ```

The objective-c code has a lot more here that I didn't fully understand but it looks like it's dealing with an OSStatus error. Why the difference?

---

*[byuSuite/Classes/CredentialManager/Keychain.swift, line 28 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaWqn8uqdzt1kIAEIG:-KiaWqn8uqdzt1kIAEIH:b-229jcg) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/Keychain.swift#L28)):*
> ```Swift
>             kSecAttrAccount as String: key,
>             kSecReturnData as String: kCFBooleanTrue,
>             kSecMatchLimit as String: kSecMatchLimitOne
> ```

Same as above, although in this case I think I can see how the code below might accomplish the same thing as the objective-c...

---

*[byuSuite/Classes/CredentialManager/Authentication/OauthTokenClient.swift, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaXhCZvzw4B1QXnMlt:-KiaXhCZvzw4B1QXnMlu:b1cf6mt) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/Authentication/OauthTokenClient.swift#L20)):*
> ```Swift
>     static func getToken(username: String?, password: String?, completionHandler: @escaping (OauthToken?, ByuError?) -> Void) {
>         //Setup the request, but then override the username and password
>         let request = setUpRequest(username: username, password: password)
> ```

Did you purposefully not setup the request body like in objective-c? If this is the case, does the comment really still apply if you're no longer setting up the request with username and password then adding them in the body?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164)*

**Comment by romrell4** [comment]
Reviewed 8 of 70 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[byuSuite/Apps/Alumni/controller/AlumniConnectViewController.swift, line 9 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaIcckMN69hTEZeB7n:-KiaaneDXiCsdGjayyTD:b2nhtan) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Apps/Alumni/controller/AlumniConnectViewController.swift#L9)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Are we not using Foundation then?
</blockquote></details>

Yup

---

*[byuSuite/Classes/byuSuite-Bridging-Header.h, line 6 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaJtY6hytQzKYcmD23:-KiaavEqzuRghqRcfob3:b2nhtan) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/e3144d0e0e7d1698d9f6330da6af98d28c2597f9/byuSuite/Classes/byuSuite-Bridging-Header.h#L6)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Do we not need this anymore?
</blockquote></details>

Yup

---

*[byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift, line 62 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaUr5MMNw1u0yIdCsk:-Kiab30yyX9n1bSEIh7u:b-90536f) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift#L62)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Have you figured it out yet or are you fine leaving this TODO in for now?
</blockquote></details>

I'll push up a new version in a moment. Don't mark this as resolved yet :)

---

*[byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift, line 66 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaV98sskyO5y3PlPFf:-KiabBeXCyPzuU7SZvOF:be3frji) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift#L66)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

I'm assuming you don't have the if !username || !password then return here anymore because you check them before ever calling this method, correct?
</blockquote></details>

Yup. In fact, it's now checked by the compiler, because the variables are "String" not "String?", so they can't be nil

---

*[byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift, line 84 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaVWAo79gJG7bADarR:-KiabIgAvbwuNfZJO1M4:b2n6zk) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift#L84)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Is this syntax correct? I don't fully understand what it's doing.
</blockquote></details>

"_" means ignore. Basically, I'll calling self.personSummary (which if you look above loads the personSummary, caches the value, and returns it. However, I don't actually need the value. "_" just means ignore the value

---

*[byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift, line 88 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaVe-19gGI0tIQvOBk:-KiabW5a1008Om3R7QT8:b8o0x97) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift#L88)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

We don't need to check that the observers respond to selectors anymore?
</blockquote></details>

Sadly not. In Swift, you can't have optional protocol methods. Not a huge deal, because everyone used the all the time anyways :)

---

*[byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift, line 95 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaVm-4_nEzufCXKWyr:-KiabqEqmEE3H4B240uM:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift#L95)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Again we don't need to check that the observers respond to selectors anymore?
</blockquote></details>

Done.

---

*[byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift, line 109 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaVuSStqmhygRJg80s:-Kiabr8KRJ5qNJ6TNe4Q:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/ByuCredentialManager2.swift#L109)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Again... not trying to be obstinate, just thorough :P 
</blockquote></details>

Done.

---

*[byuSuite/Classes/CredentialManager/Keychain.swift, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaWbBx1eEHDYCmM48B:-KiacVx-OoEiuPoA0HI0:b-budber) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/Keychain.swift#L20)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

The objective-c code has a lot more here that I didn't fully understand but it looks like it's dealing with an OSStatus error. Why the difference?
</blockquote></details>

Yup. The old code was pasted from a website. It was a redundant check. Basically, it was getting the value (if it was there). If it WAS there, it would do an update. Otherwise it would do an add. However, from my testing, it looks like add will overwrite if the value is already there. Actually, could you test this for me? Ask me if you have any questions

---

*[byuSuite/Classes/CredentialManager/Keychain.swift, line 28 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaWqn8uqdzt1kIAEIG:-Kiacu-vPfsGbZtTPdu-:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/Keychain.swift#L28)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Same as above, although in this case I think I can see how the code below might accomplish the same thing as the objective-c...
</blockquote></details>

Done.

---

*[byuSuite/Classes/CredentialManager/Authentication/OauthTokenClient.swift, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaXhCZvzw4B1QXnMlt:-Kiad0TqbK_HO_1iaHLO:bcjqxap) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/Authentication/OauthTokenClient.swift#L20)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Did you purposefully not setup the request body like in objective-c? If this is the case, does the comment really still apply if you're no longer setting up the request with username and password then adding them in the body?
</blockquote></details>

Good catch. The body is now handled through the constructor. Comment has been removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164)*

**Comment by ecbrady** [comment]
Reviewed 3 of 70 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Classes/CredentialManager/Keychain.swift, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KiaWbBx1eEHDYCmM48B:-KiagiECtt-jOpqqnEjH:b-vs1pr4) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/33425fb4c84b2970b362acf7191356329dcd1030/byuSuite/Classes/CredentialManager/Keychain.swift#L20)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Yup. The old code was pasted from a website. It was a redundant check. Basically, it was getting the value (if it was there). If it WAS there, it would do an update. Otherwise it would do an add. However, from my testing, it looks like add will overwrite if the value is already there. Actually, could you test this for me? Ask me if you have any questions
</blockquote></details>

Looks good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164)*

**Comment by ecbrady** [comment]
Reviewed 1 of 70 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164)*

**Comment by romrell4** [comment]
Reviewed 53 of 73 files at r1, 41 of 42 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164)*

**Comment by ecbrady** [comment]
Reviewed 3 of 73 files at r1, 41 of 42 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164)*

**Comment by ecbrady** [comment]
:lgtm:

---

Reviewed 3 of 42 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-:-KiavCfRhX5lCwFzEV3t:bnfp4nl)*

**Comment by ecbrady** [comment]
Reviewed 19 of 20 files at r5.
Review status: 97 of 98 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/Mpn/Device.swift, line 75 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KifrcbcaKDSDvLT--Ak:-KifrcbcaKDSDvLT--Al:bj0lzzh) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ddb35191d5ee6c57949839407bc900f8120f6df0/byuSuite/Classes/Mpn/Device.swift#L75)):*
> ```Swift
> }
> 
> extension Int {
> ```

Is this supposed to be here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164)*

**Comment by romrell4** [comment]
Review status: 97 of 98 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/Mpn/Device.swift, line 75 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-KifrcbcaKDSDvLT--Ak:-KiftFxKGfFuCO6jpbK7:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/ddb35191d5ee6c57949839407bc900f8120f6df0/byuSuite/Classes/Mpn/Device.swift#L75)):*
<details><summary><i>Previously, ecbrady (Erik Brady) wrote…</i></summary><blockquote>

Is this supposed to be here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164)*

**Comment by romrell4** [comment]
Reviewed 1 of 20 files at r5.
Review status: 95 of 98 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164)*

**Comment by ecbrady** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/164#-:-KifucmaZv0RKGzRiSZj:bnfp4nl)*

**Pull request merged**
