### PR TITLE
Add selectedYearTerm object to SemesterButton

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/22)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 30 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22#-KVaSUdP0jL8MfZ6zrfX:-KVaSUdP0jL8MfZ6zrfY:b80kqw2) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d9fd0df77d09ece8a8d6bb3d363908b9a17cd263/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L30)):*
> ```objc
>     [super viewDidLoad];
>     
>     [self setSemesterButton];
> ```

Let's call this loadSemesterButton (so that the user understands that it will do some asynchronous loading)


Actually, should we just inline this? Is it only used once?

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 107 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22#-KVaT20tabh5dJpENiV9:-KVaT20tabh5dJpENiVA:ba22xcq) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d9fd0df77d09ece8a8d6bb3d363908b9a17cd263/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L107)):*
> ```objc
> -(void)createButtonFailed:(SemesterButton *)button {
>     [self.spinner stopAnimating];
>     UIAlertView *alert = [[UIAlertView alloc] initWithTitle:nil message:@"Unable to load data." delegate:self cancelButtonTitle:@"OK" otherButtonTitles: nil];
> ```

Ugh... We need to remove this... What's the best way to remove this?

---

*[byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m, line 190 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22#-KVaTJFrmdfc17JvwaiS:-KVaTJFrmdfc17JvwaiT:b-cjb9vb) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d9fd0df77d09ece8a8d6bb3d363908b9a17cd263/byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m#L190)):*
> ```objc
> -(void)createButtonFailed:(SemesterButton *)button {
>     [self.loading stopAnimating];
>     self.alert = [[UIAlertView alloc] initWithTitle:@"Unable to Load Data" message:nil delegate:self cancelButtonTitle:@"Ok" otherButtonTitles: nil];
> ```

Upper case OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22)*

**Comment by ecbrady** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m, line 203 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22#-KVaTXKxGHJaKGiKM67q:-KVaTXKxGHJaKGiKM67r:b8z58rp) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d9fd0df77d09ece8a8d6bb3d363908b9a17cd263/byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m#L203)):*
> ```objc
>     [BYUAnalytics actionPerformedInCurrentFeature:COURSECATALOG_YEAR_TERM_SELECTED];
>     
>     if (![yearTerm.code isEqualToString:self.yearTerm.yearTerm]) {
> ```

As far as I can tell, what I have done here accomplishes the same thing they were trying to do with the for loop. This works when I test it, but if there is some reason behind their logic that you can see that I can't, I can rewrite it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22)*

**Comment by ecbrady** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 30 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22#-KVaSUdP0jL8MfZ6zrfX:-KVaVCGyZQIflCeISmRy:b-s2avco) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d9fd0df77d09ece8a8d6bb3d363908b9a17cd263/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L30)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Let's call this loadSemesterButton (so that the user understands that it will do some asynchronous loading)
> 
> 
> Actually, should we just inline this? Is it only used once?
</details>
Inlined.

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 107 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22#-KVaT20tabh5dJpENiV9:-KVaVYYr3OCgEE3zto92:b-60g2fz) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d9fd0df77d09ece8a8d6bb3d363908b9a17cd263/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L107)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Ugh... We need to remove this... What's the best way to remove this?
</details>
I tried ViewUtils but until we make this a ByuViewController we don't have the popBack ability. Would you like me to use a ViewUtils anyways?

---

*[byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m, line 190 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22#-KVaTJFrmdfc17JvwaiS:-KVaW56fKWbiQNwDtf2M:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d9fd0df77d09ece8a8d6bb3d363908b9a17cd263/byuSuite/Apps/Course Catalog/CourseCatalogDeparmentsViewController.m#L190)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Upper case OK
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 107 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22#-KVaT20tabh5dJpENiV9:-KVaWsHMOpR1fCfj-qfv:b-tjvyaa) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d9fd0df77d09ece8a8d6bb3d363908b9a17cd263/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L107)):*
<details><summary><i>Previously, ecbrady wrote…</i></summary>
> I tried ViewUtils but until we make this a ByuViewController we don't have the popBack ability. Would you like me to use a ViewUtils anyways?
</details>
Grrr... We'll have to talk about his one when I get back. Oh wait! Don't we have a delegate that is a ByuViewController?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 107 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22#-KVaT20tabh5dJpENiV9:-KVedUu6Emg-5CqXodA9:b-tnryca) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d9fd0df77d09ece8a8d6bb3d363908b9a17cd263/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L107)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Grrr... We'll have to talk about his one when I get back. Oh wait! Don't we have a delegate that is a ByuViewController?
</details>
Just put TODO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22)*

**Comment by ecbrady** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m, line 107 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22#-KVaT20tabh5dJpENiV9:-KVeeVL1HsT3_hFYTKXA:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/d9fd0df77d09ece8a8d6bb3d363908b9a17cd263/byuSuite/Apps/ByuBooklist/ByuBooklistTabBarViewController.m#L107)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Just put TODO
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/22)*

**Pull request merged**
