### PR TITLE
Hotfix/clean up classes

### PR DESCRIPTION
**Pull request by nateyj**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/94)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 95 of 100 files at r1, 46 of 46 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4o1cNilHk9gtaCHU4:-Kc4o1cNilHk9gtaCHU5:b-1jv6qp) (no related file):*
It looks like you didn't make any changes, but could you double check Job Openings and Locker Rental to make sure it works for me? Do this last, just in case you run out of time

---

*[byuSuite/Apps/AedLocator/AedLocatorViewController.m, line 126 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4nN8R-vdGwzEwSZz9:-Kc4nN8R-vdGwzEwSZzA:blsyycw) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/AedLocator/AedLocatorViewController.m#L126)):*
> ```objc
>  */
> -(void)locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status {
>     if (status != kCLAuthorizationStatusAuthorizedWhenInUse && status != kCLAuthorizationStatusAuthorizedAlways) {
> ```

Does this work? This looks like a logic change...

---

*[byuSuite/Apps/AedLocator/AedLocatorViewController.m, line 184 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4nVp1nDnDqngNrTYB:-Kc4nVp1nDnDqngNrTYC:bchb4w7) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/AedLocator/AedLocatorViewController.m#L184)):*
> ```objc
>     self.locationLabel.text = self.closestAed.properties.location;
>     [self.mapView removeAnnotations: self.mapView.annotations];
>     [self.mapView addAnnotation:self.closestAed];
> ```

zoom here?

---

*[byuSuite/Apps/AedLocator/AedLocatorViewController.m, line 216 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4nXmdBDzD09KsmB3M:-Kc4nXmdBDzD09KsmB3N:bhrf920) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/AedLocator/AedLocatorViewController.m#L216)):*
> ```objc
>                                 mapHeight);
> 
>     [self centerWithCoordinate:self.closestAed.coordinate];
> ```

What is center with coordinate? Can't zoomToFitAnnotations do that?

---

*[byuSuite/Apps/MapMyClasses/controller/MapMyClassesMapViewController.m, line 58 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4ocDq_sgTmt0D02YQ:-Kc4ocDri-M0nSzSOspn:b-89817p) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/MapMyClasses/controller/MapMyClassesMapViewController.m#L58)):*
> ```objc
>     if (classBuildings) {
>         [self.mapView addAnnotations:classBuildings];
>         //TODO: zoom to fit annotations
> ```

Do it

---

*[byuSuite/Apps/MyFinalsSchedule/controller/MyFinalsScheduleMapViewController.m, line 58 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4ohz_Txb4czMMOVs7:-Kc4ohz_Txb4czMMOVs8:b-89817p) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/MyFinalsSchedule/controller/MyFinalsScheduleMapViewController.m#L58)):*
> ```objc
>     if (finalsBuildings) {
>         [self.mapView addAnnotations:finalsBuildings];
>         //TODO: zoom to fit annotations
> ```

Do it

---

*[byuSuite/Apps/Printers/controller/PrintersMapViewController.m, line 56 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4pB2ukXft6bEAgMmt:-Kc4pB2ukXft6bEAgMmu:b-89817p) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/Printers/controller/PrintersMapViewController.m#L56)):*
> ```objc
> 			[self.mapView removeAnnotations:self.mapView.annotations];
> 			[self.mapView addAnnotations:printers];
>             //TODO: zoom to fit annotations
> ```

Do it

---

*[byuSuite/Apps/Vending/controller/VendingMapViewController.m, line 111 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4pQsoAH19fit1aUxS:-Kc4pQsoAH19fit1aUxT:b-89817p) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/Vending/controller/VendingMapViewController.m#L111)):*
> ```objc
> 	} else {
> 		[self.mapView addAnnotations:annotations];
> 		[self zoomToFitMapAnnotations]; //TODO: include user location
> ```

Do it

---

*[byuSuite/Classes/ReusableUI/ByuMapViewController.m, line 26 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4qAfqgDBbEb3P1R6W:-Kc4qAfqgDBbEb3P1R6X:b9tyiyo) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Classes/ReusableUI/ByuMapViewController.m#L26)):*
> ```objc
> -(void)viewDidLoad {
>     [super viewDidLoad];
>     [self zoomToFitMapAnnotationsWithByuInFrame:YES];
> ```

Comment about how this will start the zoom level at BYU Campus, and then will animate to other annotations when called

---

*[byuSuite/Classes/ReusableUI/ByuMapViewController.m, line 45 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4qMY_cyJ-wuIxdW1W:-Kc4qMY_cyJ-wuIxdW1X:b6he09n) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Classes/ReusableUI/ByuMapViewController.m#L45)):*
> ```objc
> 
> -(void)centerWithCoordinate:(CLLocationCoordinate2D)coordinate {
>     CLLocationDegrees delta = 0.017;
> ```

Can we #define this? What is it being used for?

---

*[byuSuite/Classes/ReusableUI/ByuWebView.m, line 93 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4qWdEuRlr3AHVXo7S:-Kc4qWdEuRlr3AHVXo7T:b-be7ovy) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Classes/ReusableUI/ByuWebView.m#L93)):*
> ```objc
>     if ([self.delegate respondsToSelector:@selector(webView:didFailLoadWithError:)]) {
>         //error alert triggered and shown in ByuWebViewController -webView:didFailLoadWithError:
>         [self.delegate webView:self didFailLoadWithError:[[NSError alloc] init]];
> ```

Can we not pass back nil?

---

*[byuSuite/Classes/ReusableUI/Buildings/CampusBuildingsMapViewController.m, line 47 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4qk_9AE_aKdktMCj3:-Kc4qk_9AE_aKdktMCj4:b3ltytp) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Classes/ReusableUI/Buildings/CampusBuildingsMapViewController.m#L47)):*
> ```objc
>     if (self.building) {
>         [self.mapView addAnnotation:self.building];
>         [self centerWithCoordinate:self.building.coordinate];
> ```

Can this not be done with our zoom function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94)*

**Comment by nateyj** [comment]
Review status: 104 of 115 files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4o1cNilHk9gtaCHU4:-Kc56B7CUGWMgTI7KwYA:b8ga1ta) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

It looks like you didn't make any changes, but could you double check Job Openings and Locker Rental to make sure it works for me? Do this last, just in case you run out of time
</blockquote></details>

Yeah I didn't make any changes other than renaming and reorganizing the file structure

---

*[byuSuite/Apps/AedLocator/AedLocatorViewController.m, line 126 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4nN8R-vdGwzEwSZz9:-Kc56MXJHM9xTDq5fkcq:b-oubt8o) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/AedLocator/AedLocatorViewController.m#L126)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Does this work? This looks like a logic change...
</blockquote></details>

It does work and it is a logic change. I had to remove an obsolete function and it took me a while to understand  how it was being used and when and stuff like that so I redid the logic to better without using it too

---

*[byuSuite/Apps/AedLocator/AedLocatorViewController.m, line 184 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4nVp1nDnDqngNrTYB:-Kc57KlLEdqJt5M7sGEo:b-7g4owm) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/AedLocator/AedLocatorViewController.m#L184)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

zoom here?
</blockquote></details>

Nope. -updateLayout gets called and that's where it should happen

---

*[byuSuite/Apps/AedLocator/AedLocatorViewController.m, line 216 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4nXmdBDzD09KsmB3M:-Kc57UYLXHCO5gB8Ls0_:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/AedLocator/AedLocatorViewController.m#L216)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is center with coordinate? Can't zoomToFitAnnotations do that?
</blockquote></details>

Done.

---

*[byuSuite/Apps/MapMyClasses/controller/MapMyClassesMapViewController.m, line 58 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4ocDq_sgTmt0D02YQ:-Kc5Eq7A0Voe5waGBqoD:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/MapMyClasses/controller/MapMyClassesMapViewController.m#L58)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

Done.

---

*[byuSuite/Apps/MyFinalsSchedule/controller/MyFinalsScheduleMapViewController.m, line 58 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4ohz_Txb4czMMOVs7:-Kc5ARsvM2PhIdPkaQTN:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/MyFinalsSchedule/controller/MyFinalsScheduleMapViewController.m#L58)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

Done.

---

*[byuSuite/Apps/Printers/controller/PrintersMapViewController.m, line 56 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4pB2ukXft6bEAgMmt:-Kc5ArCpp80mYgr9i2SD:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/Printers/controller/PrintersMapViewController.m#L56)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

Done.

---

*[byuSuite/Apps/Vending/controller/VendingMapViewController.m, line 111 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4pQsoAH19fit1aUxS:-Kc5BO5oQgTspVghdlwR:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Apps/Vending/controller/VendingMapViewController.m#L111)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

Done.

---

*[byuSuite/Classes/ReusableUI/ByuMapViewController.m, line 26 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4qAfqgDBbEb3P1R6W:-Kc5DpEEmTva2DYUoMEZ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Classes/ReusableUI/ByuMapViewController.m#L26)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment about how this will start the zoom level at BYU Campus, and then will animate to other annotations when called
</blockquote></details>

Done.

---

*[byuSuite/Classes/ReusableUI/ByuMapViewController.m, line 45 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4qMY_cyJ-wuIxdW1W:-Kc5DwoO7fFSwK0QqAHB:b-7n87ov) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Classes/ReusableUI/ByuMapViewController.m#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can we #define this? What is it being used for?
</blockquote></details>

We can if you want. It's only ever being used in this one function. We need it in order to have the zoom level specified when the map is centered on a coordinate

---

*[byuSuite/Classes/ReusableUI/ByuWebView.m, line 93 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4qWdEuRlr3AHVXo7S:-Kc5EFWI-M-kYLBDWR_m:b2r0tz1) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Classes/ReusableUI/ByuWebView.m#L93)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can we not pass back nil?
</blockquote></details>

Nope. It's non-nullable

---

*[byuSuite/Classes/ReusableUI/Buildings/CampusBuildingsMapViewController.m, line 47 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94#-Kc4qk_9AE_aKdktMCj3:-Kc5EegjY-IZUJ-MIk6B:b-k1ka2x) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/8ccd73f3a412eda37897fb6698867a0b0cf0e59c/byuSuite/Classes/ReusableUI/Buildings/CampusBuildingsMapViewController.m#L47)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can this not be done with our zoom function?
</blockquote></details>

Nope, because it zooms in too close and shows a grid instead of a map

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94)*

**Comment by romrell4** [comment]
Reviewed 15 of 16 files at r3.
Review status: 116 of 117 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94)*

**Comment by romrell4** [comment]
Reviewed 1 of 16 files at r3.
Review status: 116 of 117 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/94)*

**Pull request merged**
