### PR TITLE
Hotfix/swift

### PR DESCRIPTION
**Pull request by nateyj**
I'm almost positive it's in a working, buildable state. I figured I'd start the PR so you could get started on it

---
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/ios-byusuite/151)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/LabComputers/model/ComputerLab.swift, line 12 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki0kfqtp5_pGeXIxppp:-Ki0kfquArfTDW6M6cRa:b-pa5fl4) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/32f5356d3aed3c95ea8d5d3a374bbc587de0dd83/byuSuite/Apps/LabComputers/model/ComputerLab.swift#L12)):*
> ```Swift
> import Foundation
> 
> //TODO: inherits from NSObject to be accessible in Objective-C, not needed when Swift only
> ```

Can we remove this now that LabComputers is all swift?

---

*[byuSuite/Classes/ByuRequest-Swift/ByuNetworkActivityIndicator.swift, line 12 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki0kyxPcKs3FZrmbORP:-Ki0kyxPcKs3FZrmbORQ:bu32fq8) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/32f5356d3aed3c95ea8d5d3a374bbc587de0dd83/byuSuite/Classes/ByuRequest-Swift/ByuNetworkActivityIndicator.swift#L12)):*
> ```Swift
> import Foundation
> 
> //TODO: inherits from NSObject to be accessible in Objective-C, not needed when Swift only
> ```

Is this still needed now that we moved the webview and byuviewcontroller to swift

---

*[byuSuite/Classes/ByuRequest-Swift/ByuRequest2.swift, line 69 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki0lOiR7qMxZToAjXIv:-Ki0lOiR7qMxZToAjXIw:bh4zjbg) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/32f5356d3aed3c95ea8d5d3a374bbc587de0dd83/byuSuite/Classes/ByuRequest-Swift/ByuRequest2.swift#L69)):*
> ```Swift
>         
>         //Must be called after non-optonal properties have been initialized, but before any methods can be called on self
>         super.init()
> ```

Why is this? Could you explain this to me? I haven't had to use this in the past...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151)*

**Comment by nateyj** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/LabComputers/model/ComputerLab.swift, line 12 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki0kfqtp5_pGeXIxppp:-Ki1p9iULwoi-kbB2Sj6:b-gnryze) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/32f5356d3aed3c95ea8d5d3a374bbc587de0dd83/byuSuite/Apps/LabComputers/model/ComputerLab.swift#L12)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can we remove this now that LabComputers is all swift?
</blockquote></details>

Good catch. Yes we can

---

*[byuSuite/Classes/ByuRequest-Swift/ByuNetworkActivityIndicator.swift, line 12 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki0kyxPcKs3FZrmbORP:-Ki1oNe1Z6RygEwAuFKd:bk4utmq) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/32f5356d3aed3c95ea8d5d3a374bbc587de0dd83/byuSuite/Classes/ByuRequest-Swift/ByuNetworkActivityIndicator.swift#L12)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is this still needed now that we moved the webview and byuviewcontroller to swift
</blockquote></details>

`ByuWebView` is actually still in Objective-C... so it still needs to inherit from `NSObject`. `ByuWebView` uses Swift stuff like the new `ByuError` but the file itself is still in Objective-C

---

*[byuSuite/Classes/ByuRequest-Swift/ByuRequest2.swift, line 69 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki0lOiR7qMxZToAjXIv:-Ki1n6PC1GYE0X3KWEjS:b-ufzlsw) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/32f5356d3aed3c95ea8d5d3a374bbc587de0dd83/byuSuite/Classes/ByuRequest-Swift/ByuRequest2.swift#L69)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why is this? Could you explain this to me? I haven't had to use this in the past...
</blockquote></details>

It's mainly because `ByuRequest2` inherits from NSObject. The code didn't need it before, but now every property needs to be initialized before using `self` in the `init`. I'm not exactly sure why though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/ByuRequest-Swift/ByuRequest2.swift, line 69 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki0lOiR7qMxZToAjXIv:-Ki1rIe9F-y1UaAH2gl0:bfk2ff2) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/32f5356d3aed3c95ea8d5d3a374bbc587de0dd83/byuSuite/Classes/ByuRequest-Swift/ByuRequest2.swift#L69)):*
<details><summary><i>Previously, nateyj (Nathan Johnson) wrote…</i></summary><blockquote>

It's mainly because `ByuRequest2` inherits from NSObject. The code didn't need it before, but now every property needs to be initialized before using `self` in the `init`. I'm not exactly sure why though
</blockquote></details>

Let's look at this one together when we're in the office at the same time. When are you working now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151)*

**Comment by romrell4** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151)*

**Comment by romrell4** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151)*

**Comment by nateyj** [comment]
Review status: 3 of 53 files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Classes/ByuRequest-Swift/ByuRequest2.swift, line 69 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki0lOiR7qMxZToAjXIv:-Ki71-R3XKXVhLt_F3i6:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/32f5356d3aed3c95ea8d5d3a374bbc587de0dd83/byuSuite/Classes/ByuRequest-Swift/ByuRequest2.swift#L69)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's look at this one together when we're in the office at the same time. When are you working now?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151)*

**Comment by romrell4** [comment]
Reviewed 49 of 50 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 114 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki77WQjKn8XlgvjiwFJ:-Ki77WQjKn8XlgvjiwFK:b-89817p) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/98f595798a8d8663709946f01fe214324faa6055/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L114)):*
> ```Swift
>     
>     func showContactOptionsActionSheet(cell: UITableViewCell?) {
>         guard let tableViewCell = cell else { return } //TODO: handle error
> ```

Do it

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 124 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki77Y0ljpnmHHJIBmjm:-Ki77Y0ljpnmHHJIBmjn:b-89817p) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/98f595798a8d8663709946f01fe214324faa6055/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L124)):*
> ```Swift
>     
>     func showReportViolationContactOptionsActionSheet(cell: UITableViewCell?) {
>         guard let tableViewCell = cell else { return } //TODO: handle error
> ```

Do it

---

*[byuSuite/Apps/DepartmentDirectory/controller/DepartmentDirectoryListingViewController.m, line 146 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki77dFOcTldO2Wvwyfn:-Ki77dFOcTldO2Wvwyfo:bynilvn) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/98f595798a8d8663709946f01fe214324faa6055/byuSuite/Apps/DepartmentDirectory/controller/DepartmentDirectoryListingViewController.m#L146)):*
> ```objc
>                 [self performSegueWithIdentifier:SHOW_MAP_SEGUE_ID sender:building];
>             } else {
>                 [self showError:[[ByuError alloc] initWithError:nil readableMessage:@"The location you selected is not currently tracked by our system." debugMessage:nil] withTitle:@"Could Not Find Location" andCallback:^(UIAlertAction *action) {
> ```

Wait... Is this using swift? Or is this still objective-c ByuError?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151)*

**Comment by nateyj** [comment]
Review status: 46 of 106 files reviewed at latest revision, 3 unresolved discussions.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 114 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki77WQjKn8XlgvjiwFJ:-Ki7RYT9fKs1CpLJxWSK:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/98f595798a8d8663709946f01fe214324faa6055/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L114)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

Done.

---

*[byuSuite/Apps/Copyright/controller/CopyrightViewController.swift, line 124 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki77Y0ljpnmHHJIBmjm:-Ki7RXq69gUBDyCiTgTA:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/98f595798a8d8663709946f01fe214324faa6055/byuSuite/Apps/Copyright/controller/CopyrightViewController.swift#L124)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

Done.

---

*[byuSuite/Apps/DepartmentDirectory/controller/DepartmentDirectoryListingViewController.m, line 146 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki77dFOcTldO2Wvwyfn:-Ki7R_aSwicbUHLx5mo0:b-80sicy) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/98f595798a8d8663709946f01fe214324faa6055/byuSuite/Apps/DepartmentDirectory/controller/DepartmentDirectoryListingViewController.m#L146)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Wait... Is this using swift? Or is this still objective-c ByuError?
</blockquote></details>

Swift

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151)*

**Comment by romrell4** [comment]
Reviewed 60 of 60 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/TestingCenter/controller/TestingCenterScoresViewController.m, line 15 at r7](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki7SEKi3h4n7X-_w375:-Ki7SEKi3h4n7X-_w376:bw5v6np) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/452fe087d72db13aef40b39de6d236208adccf92/byuSuite/Apps/TestingCenter/controller/TestingCenterScoresViewController.m#L15)):*
> ```objc
> #import "NSArray+higherOrder.h"
> #import "SemesterButton.h"
> #import "byuSuite-Swift.h"
> ```

Do we need this here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151)*

**Comment by nateyj** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[byuSuite/Apps/TestingCenter/controller/TestingCenterScoresViewController.m, line 15 at r7](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151#-Ki7SEKi3h4n7X-_w375:-Ki7T9TwZFB-12ggKQze:b-896fix) ([raw file](https://github.com/byu-oit-appdev/ios-byusuite/blob/452fe087d72db13aef40b39de6d236208adccf92/byuSuite/Apps/TestingCenter/controller/TestingCenterScoresViewController.m#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we need this here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151)*

**Comment by romrell4** [comment]
Reviewed 1 of 60 files at r7.
Review status: 104 of 106 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/ios-byusuite/151)*

**Pull request merged**
